//---------------------------------------------------------------------------*
//                                                                           *
//                             File 'communs.h'                              *
//                        Generated by version 2.5.0                         *
//                      august 5th, 2013, at 10h42'4"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef communs_ENTITIES_DEFINED
#define communs_ENTITIES_DEFINED

//---------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------*

#include "piccolo_lexique.h"

//---------------------------------------------------------------------------*

#include "pic18_metamodel.h"
#include "generic_metamodel.h"

//---------------------------------------------------------------------------*

class GALGAS__32_stringlist ;
class GALGAS__32_stringlist_2E_element ;
class GALGAS_FA_5F_instruction_5F_base_5F_code ;
class GALGAS_actualConfigurationMap ;
class GALGAS_actualConfigurationMap_2E_element ;
class GALGAS_andCondition ;
class GALGAS_application ;
class GALGAS_bcc_5F_in_5F_structured_5F_if_5F_condition ;
class GALGAS_binaryset ;
class GALGAS_bitNumberExpression ;
class GALGAS_bitNumberLabelValue ;
class GALGAS_bitNumberLiteralValue ;
class GALGAS_bitSliceTable ;
class GALGAS_bitSliceTable_2E_element ;
class GALGAS_bitTest_5F_in_5F_structured_5F_if_5F_condition ;
class GALGAS_bit_5F_oriented_5F_op ;
class GALGAS_bool ;
class GALGAS_bootloaderReservedRAMmap ;
class GALGAS_bootloaderReservedRAMmap_2E_element ;
class GALGAS_byteDeclarationInRam ;
class GALGAS_char ;
class GALGAS_checkpicList ;
class GALGAS_checkpicList_2E_element ;
class GALGAS_conditionExpression ;
class GALGAS_conditional_5F_branch ;
class GALGAS_configDefinitionList ;
class GALGAS_configDefinitionList_2E_element ;
class GALGAS_configSettingList ;
class GALGAS_configSettingList_2E_element ;
class GALGAS_constantDefinitionList ;
class GALGAS_constantDefinitionList_2E_element ;
class GALGAS_data ;
class GALGAS_dataList ;
class GALGAS_dataList_2E_element ;
class GALGAS_dataMap ;
class GALGAS_dataMap_2E_element ;
class GALGAS_declarationInRam ;
class GALGAS_declarationInRamList ;
class GALGAS_declarationInRamList_2E_element ;
class GALGAS_double ;
class GALGAS_filewrapper ;
class GALGAS_function ;
class GALGAS_functionlist ;
class GALGAS_functionlist_2E_element ;
class GALGAS_if_5F_semi_5F_colon_5F_op ;
class GALGAS_immediatAdd ;
class GALGAS_immediatAnd ;
class GALGAS_immediatComplement ;
class GALGAS_immediatDiv ;
class GALGAS_immediatEqualTest ;
class GALGAS_immediatExpression ;
class GALGAS_immediatExpressionList ;
class GALGAS_immediatExpressionList_2E_element ;
class GALGAS_immediatGreaterOrEqualTest ;
class GALGAS_immediatGreaterTest ;
class GALGAS_immediatInteger ;
class GALGAS_immediatLeftShift ;
class GALGAS_immediatLowerOrEqualTest ;
class GALGAS_immediatLowerTest ;
class GALGAS_immediatMod ;
class GALGAS_immediatMul ;
class GALGAS_immediatNegate ;
class GALGAS_immediatNotEqualTest ;
class GALGAS_immediatOr ;
class GALGAS_immediatRegister ;
class GALGAS_immediatRightShift ;
class GALGAS_immediatSlice ;
class GALGAS_immediatSliceExpressionList ;
class GALGAS_immediatSliceExpressionList_2E_element ;
class GALGAS_immediatSub ;
class GALGAS_immediatXor ;
class GALGAS_incDecRegisterInCondition ;
class GALGAS_instructionList ;
class GALGAS_instructionList_2E_element ;
class GALGAS_instruction_5F_FA ;
class GALGAS_instruction_5F_FBA ;
class GALGAS_instruction_5F_FDA ;
class GALGAS_instruction_5F_FDA_5F_base_5F_code_5F_AST ;
class GALGAS_instruction_5F_FOREVER ;
class GALGAS_instruction_5F_IF_5F_BitTest ;
class GALGAS_instruction_5F_IF_5F_FA_5F_SEMI_5F_COLON ;
class GALGAS_instruction_5F_IF_5F_IncDec ;
class GALGAS_instruction_5F_IF_5F_SEMI_5F_COLON ;
class GALGAS_instruction_5F_JSR ;
class GALGAS_instruction_5F_JUMP ;
class GALGAS_instruction_5F_JUMPCC ;
class GALGAS_instruction_5F_LDATAPTR ;
class GALGAS_instruction_5F_LFSR ;
class GALGAS_instruction_5F_LTBLPTR ;
class GALGAS_instruction_5F_MNOP ;
class GALGAS_instruction_5F_MOVFF ;
class GALGAS_instruction_5F_TBLRD ;
class GALGAS_instruction_5F_TBLWT ;
class GALGAS_instruction_5F_banksel ;
class GALGAS_instruction_5F_banksel_5F_register ;
class GALGAS_instruction_5F_computed_5F_bra ;
class GALGAS_instruction_5F_computed_5F_goto ;
class GALGAS_instruction_5F_computed_5F_rcall ;
class GALGAS_instruction_5F_computed_5F_retlw ;
class GALGAS_instruction_5F_do_5F_while ;
class GALGAS_instruction_5F_literalOperation ;
class GALGAS_instruction_5F_nobanksel ;
class GALGAS_instruction_5F_savebank ;
class GALGAS_instruction_5F_structured_5F_if ;
class GALGAS_instruction_5F_withNoOperand ;
class GALGAS_interruptDefinitionList ;
class GALGAS_interruptDefinitionList_2E_element ;
class GALGAS_jumpInstructionKind ;
class GALGAS_lbool ;
class GALGAS_lchar ;
class GALGAS_ldouble ;
class GALGAS_literal_5F_instruction_5F_opcode ;
class GALGAS_location ;
class GALGAS_lsint ;
class GALGAS_lsint_36__34_ ;
class GALGAS_lstring ;
class GALGAS_lstringlist ;
class GALGAS_lstringlist_2E_element ;
class GALGAS_luint ;
class GALGAS_luint_36__34_ ;
class GALGAS_luintlist ;
class GALGAS_luintlist_2E_element ;
class GALGAS_negateCondition ;
class GALGAS_object ;
class GALGAS_objectlist ;
class GALGAS_objectlist_2E_element ;
class GALGAS_partList ;
class GALGAS_partList_2E_element ;
class GALGAS_pic_31__38_InstructionWithNoOperandKind ;
class GALGAS_pic_31__38_PiccoloInstruction ;
class GALGAS_pic_31__38_PiccoloSimpleInstruction ;
class GALGAS_pic_31__38_RegisterComparison ;
class GALGAS_piccoloModel ;
class GALGAS_programKind ;
class GALGAS_ramDefinitionList ;
class GALGAS_ramDefinitionList_2E_element ;
class GALGAS_range ;
class GALGAS_registerComparisonCondition ;
class GALGAS_registerExpression ;
class GALGAS_registerTestCondition ;
class GALGAS_routineDeclarationList ;
class GALGAS_routineDeclarationList_2E_element ;
class GALGAS_routineDefinitionList ;
class GALGAS_routineDefinitionList_2E_element ;
class GALGAS_sint ;
class GALGAS_sint_36__34_ ;
class GALGAS_string ;
class GALGAS_stringlist ;
class GALGAS_stringlist_2E_element ;
class GALGAS_stringset ;
class GALGAS_tableAccessOption ;
class GALGAS_type ;
class GALGAS_typelist ;
class GALGAS_typelist_2E_element ;
class GALGAS_uint ;
class GALGAS_uint_36__34_ ;
class GALGAS_uint_36__34_list ;
class GALGAS_uint_36__34_list_2E_element ;
class GALGAS_uintlist ;
class GALGAS_uintlist_2E_element ;

//---------------------------------------------------------------------------*
//                                                                           *
//                    Parser class 'communs' declaration                     *
//                                                                           *
//---------------------------------------------------------------------------*

class cParser_communs {
//--- Virtual destructor
  public : virtual ~ cParser_communs (void) {}

//--- Non terminal declarations
  protected : virtual void nt_bit_5F_number_5F_parsing_ (GALGAS_bitNumberExpression & outArgument0,
                                                         C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_bit_5F_number_5F_parsing_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_configuration_5F_definition_ (GALGAS_configDefinitionList & ioArgument0,
                                                            C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_configuration_5F_definition_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_constant_5F_definition_ (GALGAS_constantDefinitionList & ioArgument0,
                                                       C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_constant_5F_definition_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_declaration_5F_in_5F_ram_ (GALGAS_declarationInRam & outArgument0,
                                                         C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_declaration_5F_in_5F_ram_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_bitwise_5F_factor_ (GALGAS_immediatExpression & outArgument0,
                                                               C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_bitwise_5F_factor_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_bitwise_5F_term_ (GALGAS_immediatExpression & outArgument0,
                                                             C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_bitwise_5F_term_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_expression_ (GALGAS_immediatExpression & outArgument0,
                                                        C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_expression_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_factor_ (GALGAS_immediatExpression & outArgument0,
                                                    C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_factor_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_primary_ (GALGAS_immediatExpression & outArgument0,
                                                     C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_primary_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_term_ (GALGAS_immediatExpression & outArgument0,
                                                  C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_immediate_5F_term_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_optional_5F_w_5F_as_5F_dest_ (GALGAS_bool & outArgument0,
                                                            C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_optional_5F_w_5F_as_5F_dest_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_ram_5F_definition_ (GALGAS_ramDefinitionList & ioArgument0,
                                                  C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_ram_5F_definition_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_register_5F_parsing_ (GALGAS_registerExpression & outArgument0,
                                                    C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;

  protected : virtual void nt_register_5F_parsing_parse (C_Lexique_piccolo_5F_lexique * inLexique) = 0 ;


//--- Rule declarations
  protected : void rule_communs_configuration_5F_definition_i0_ (GALGAS_configDefinitionList & ioArgument0,
                                                                 C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_configuration_5F_definition_i0_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_declaration_5F_in_5F_ram_i1_ (GALGAS_declarationInRam & outArgument0,
                                                              C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_declaration_5F_in_5F_ram_i1_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_ram_5F_definition_i2_ (GALGAS_ramDefinitionList & ioArgument0,
                                                       C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_ram_5F_definition_i2_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_constant_5F_definition_i3_ (GALGAS_constantDefinitionList & ioArgument0,
                                                            C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_constant_5F_definition_i3_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_expression_i4_ (GALGAS_immediatExpression & outArgument0,
                                                             C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_expression_i4_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_bitwise_5F_term_i5_ (GALGAS_immediatExpression & outArgument0,
                                                                  C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_bitwise_5F_term_i5_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_bitwise_5F_factor_i6_ (GALGAS_immediatExpression & outArgument0,
                                                                    C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_bitwise_5F_factor_i6_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_term_i7_ (GALGAS_immediatExpression & outArgument0,
                                                       C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_term_i7_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_factor_i8_ (GALGAS_immediatExpression & outArgument0,
                                                         C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_factor_i8_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_primary_i9_ (GALGAS_immediatExpression & outArgument0,
                                                          C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_immediate_5F_primary_i9_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_register_5F_parsing_i10_ (GALGAS_registerExpression & outArgument0,
                                                          C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_register_5F_parsing_i10_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_bit_5F_number_5F_parsing_i11_ (GALGAS_bitNumberExpression & outArgument0,
                                                               C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_bit_5F_number_5F_parsing_i11_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_bit_5F_number_5F_parsing_i12_ (GALGAS_bitNumberExpression & outArgument0,
                                                               C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_bit_5F_number_5F_parsing_i12_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_optional_5F_w_5F_as_5F_dest_i13_ (GALGAS_bool & outArgument0,
                                                                  C_Lexique_piccolo_5F_lexique * inLexique) ;

  protected : void rule_communs_optional_5F_w_5F_as_5F_dest_i13_parse (C_Lexique_piccolo_5F_lexique * inLexique) ;



//--- Select methods
  protected : virtual PMSInt32 select_communs_0 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_1 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_2 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_3 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_4 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_5 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_6 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_7 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_8 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_9 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_10 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_11 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_12 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_13 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_14 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_15 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_16 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_17 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_18 (C_Lexique_piccolo_5F_lexique *) = 0 ;

  protected : virtual PMSInt32 select_communs_19 (C_Lexique_piccolo_5F_lexique *) = 0 ;


} ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
