//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_bitNumberLabelValue.h'                    *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                      july 21th, 2008, at 16h45'26"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                abstract class 'cPtr_bitNumberLabelValue'                  *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_bitNumberLabelValue : public cPtr_bitNumberExpression {
  private : typedef cPtr_bitNumberExpression inherited ;
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Constructor
  public : cPtr_bitNumberLabelValue (const GGS_lstring & ,
                                const GGS_luint & 
                                COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~cPtr_bitNumberLabelValue (void) {}
  #endif

//--- Attributes
  public : GGS_lstring  mBitNumberLabelValue ;
  public : GGS_luint  mBitNumberIndexValue ;
//--- Class message
  public : virtual const char * _message (void) const ;
  public : static const char * _static_message (void) ;

//--- Method for 'description' reader
  public : virtual void
  appendForDescription (C_Compiler & _inLexique,
                        C_String & ioString,
                        const sint32 inIndentation
                        COMMA_LOCATION_ARGS) const ;

//--- Comparison
  public : virtual bool
  isEqualToObject (const cPtr__AC_galgas_class * inOperand) const ;

//--- Galgas RTTI
  public : virtual AC_galgasClassRunTimeInformation * galgasRTTI (void) const ;
} ;

//---------------------------------------------------------------------------*

