//---------------------------------------------------------------------------*
//                                                                           *
//                     File 'ipc18_convert_relatives.h'                      *
//             Generated by version version GALGAS_BETA_VERSION              *
//                       may 13th, 2011, at 13h45'22"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef ipc18_convert_relatives_ENTITIES_DEFINED
#define ipc18_convert_relatives_ENTITIES_DEFINED

//---------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------*

#include "ipic18_metamodel.h"
#include "pic18_metamodel.h"
#include "generic_metamodel.h"
#include "ipic_generic.h"
#include "piccoloDevice_semantics.h"

//---------------------------------------------------------------------------*

class GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives ;
class GALGAS_toto ;
class GALGAS_toto_31_ ;
class GALGAS_toto_32_ ;
class GALGAS_toto_33_ ;

//---------------------------------------------------------------------------*
//                                                                           *
//               @ipic18_symbolTableForConvertingRelatives map               *
//                                                                           *
//---------------------------------------------------------------------------*

class cMapElement_ipic_31__38__5F_symbolTableForConvertingRelatives ;

//---------------------------------------------------------------------------*

extern const char * kSearchErrorMessage_ipic_31__38__5F_symbolTableForConvertingRelatives_searchKey ;

//---------------------------------------------------------------------------*

class GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives : public AC_GALGAS_map {
//--------------------------------- Default constructor
  public : GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives (void) ;

//--------------------------------- Handle copy
  public : GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives (const GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & inSource) ;
  public : GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & operator = (const GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & inSource) ;

//-- Start of generic part --*

//--------------------------------- Object cloning
  protected : virtual AC_GALGAS_root * clonedObject (void) const ;

//--------------------------------- Object extraction
  public : static GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives extractObject (const GALGAS_object & inObject,
                                                                                          C_Compiler * inCompiler,
                                                                                          const GALGAS_location & inErrorLocation
                                                                                          COMMA_LOCATION_ARGS) ;

//--------------------------------- GALGAS constructors
  public : static GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives constructor_emptyMap (LOCATION_ARGS) ;

  public : static GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives constructor_mapWithMapToOverride (const GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & inOperand0
                                                                                                             COMMA_LOCATION_ARGS) ;


//--------------------------------- Modifiers
  public : VIRTUAL_IN_DEBUG void modifier_insertKey (GALGAS_lstring constinArgument0,
                                                     GALGAS_uint constinArgument1,
                                                     C_Compiler * inCompiler
                                                     COMMA_LOCATION_ARGS) ;

  public : VIRTUAL_IN_DEBUG void modifier_setMRoutineAddressForKey (GALGAS_uint constinArgument0,
                                                                    GALGAS_string constinArgument1,
                                                                    C_Compiler * inCompiler
                                                                    COMMA_LOCATION_ARGS) ;


//--------------------------------- Instance Methods
  public : VIRTUAL_IN_DEBUG void method_searchKey (GALGAS_lstring constinArgument0,
                                                   GALGAS_uint & outArgument1,
                                                   C_Compiler * inCompiler
                                                   COMMA_LOCATION_ARGS) const ;

//--------------------------------- Class Methods

//--------------------------------- Readers
  public : VIRTUAL_IN_DEBUG GALGAS_uint reader_mRoutineAddressForKey (const GALGAS_string & constinOperand0,
                                                                      C_Compiler * inCompiler
                                                                      COMMA_LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives reader_overriddenMap (LOCATION_ARGS) const ;


//--------------------------------- Introspection
  public : VIRTUAL_IN_DEBUG const C_galgas_type_descriptor * staticTypeDescriptor (void) const ;
//--------------------------------- 'with' accessors
  public : VIRTUAL_IN_DEBUG cMapElement_ipic_31__38__5F_symbolTableForConvertingRelatives * readWriteAccessForWithInstruction_hasKey (C_Compiler * inCompiler,
                                                                                                                                      const GALGAS_string & inKey
                                                                                                                                      COMMA_LOCATION_ARGS) ;

  public : VIRTUAL_IN_DEBUG cMapElement_ipic_31__38__5F_symbolTableForConvertingRelatives * readWriteAccessForWithInstruction_searchKey (C_Compiler * inCompiler,
                                                                                                                                         const GALGAS_lstring & inKey
                                                                                                                                         COMMA_LOCATION_ARGS) ;

//--------------------------------- Friend

  friend class cEnumerator_ipic_31__38__5F_symbolTableForConvertingRelatives ;
 
} ; // End of GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives class

//---------------------------------------------------------------------------*
//   Enumerator declaration                                                  *
//---------------------------------------------------------------------------*

class cEnumerator_ipic_31__38__5F_symbolTableForConvertingRelatives : public cGenericAbstractEnumerator {
  public : cEnumerator_ipic_31__38__5F_symbolTableForConvertingRelatives (const GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & inEnumeratedObject,
                                                                          const typeEnumerationOrder inOrder) ;

//--- Current element access
  public : GALGAS_lstring current_lkey (LOCATION_ARGS) const ;
  public : GALGAS_uint current_mRoutineAddress (LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

extern const C_galgas_type_descriptor kTypeDescriptor_GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives ;

//--------------------------------- 'with' accessors
cCollectionElement * readWriteAccessForWithInstruction_hasKey (C_Compiler * inCompiler,
                                                               GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & ioMap,
                                                               GALGAS_string & inKey
                                                               COMMA_LOCATION_ARGS) ;

cCollectionElement * readWriteAccessForWithInstruction_searchKey (C_Compiler * inCompiler,
                                                                  GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & ioMap,
                                                                  GALGAS_lstring & inKey
                                                                  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//        Routine 'ipic18_convertRelativeBranchsToAbsoluteWhenNeeded'        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_ipic_31__38__5F_convertRelativeBranchsToAbsoluteWhenNeeded (GALGAS_ipic_31__38__5F_instructionList & ioArgument0,
                                                                         GALGAS_string & ioArgument1,
                                                                         C_Compiler * inCompiler
                                                                         COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                                @toto class                                *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto ;

//---------------------------------------------------------------------------*

class GALGAS_toto : public AC_GALGAS_class {
//--- Constructor
  public : GALGAS_toto (void) ;

//---
  public : inline const cPtr_toto * ptr (void) const { return (const cPtr_toto *) mObjectPtr ; }

//--------------------------------- Constructor from pointer
  public : GALGAS_toto (const cPtr_toto * inSourcePtr) ;



//-- Start of generic part --*

//--------------------------------- Object cloning
  protected : virtual AC_GALGAS_root * clonedObject (void) const ;

//--------------------------------- Object extraction
  public : static GALGAS_toto extractObject (const GALGAS_object & inObject,
                                             C_Compiler * inCompiler,
                                             const GALGAS_location & inErrorLocation
                                             COMMA_LOCATION_ARGS) ;

//--------------------------------- Comparison
  public : typeComparisonResult objectCompare (const GALGAS_toto & inOperand) const ;

//--------------------------------- Modifiers

//--------------------------------- Instance Methods
//--------------------------------- Class Methods

//--------------------------------- Readers

//--------------------------------- Introspection
  public : VIRTUAL_IN_DEBUG const C_galgas_type_descriptor * staticTypeDescriptor (void) const ;
 
} ; // End of GALGAS_toto class


//---------------------------------------------------------------------------*

extern const C_galgas_type_descriptor kTypeDescriptor_GALGAS_toto ;

//---------------------------------------------------------------------------*
//                                                                           *
//                              @toto_31_ class                              *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto_31_ ;

//---------------------------------------------------------------------------*

class GALGAS_toto_31_ : public GALGAS_toto {
//--- Constructor
  public : GALGAS_toto_31_ (void) ;

//---
  public : inline const cPtr_toto_31_ * ptr (void) const { return (const cPtr_toto_31_ *) mObjectPtr ; }

//--------------------------------- Constructor from pointer
  public : GALGAS_toto_31_ (const cPtr_toto_31_ * inSourcePtr) ;



//-- Start of generic part --*

//--------------------------------- Object cloning
  protected : virtual AC_GALGAS_root * clonedObject (void) const ;

//--------------------------------- Object extraction
  public : static GALGAS_toto_31_ extractObject (const GALGAS_object & inObject,
                                                 C_Compiler * inCompiler,
                                                 const GALGAS_location & inErrorLocation
                                                 COMMA_LOCATION_ARGS) ;

//--------------------------------- GALGAS constructors
  public : static GALGAS_toto_31_ constructor_new (LOCATION_ARGS) ;

//--------------------------------- Comparison
  public : typeComparisonResult objectCompare (const GALGAS_toto_31_ & inOperand) const ;

//--------------------------------- Modifiers

//--------------------------------- Instance Methods
//--------------------------------- Class Methods

//--------------------------------- Readers

//--------------------------------- Introspection
  public : VIRTUAL_IN_DEBUG const C_galgas_type_descriptor * staticTypeDescriptor (void) const ;
 
} ; // End of GALGAS_toto_31_ class


//---------------------------------------------------------------------------*

extern const C_galgas_type_descriptor kTypeDescriptor_GALGAS_toto_31_ ;

//---------------------------------------------------------------------------*
//                                                                           *
//                              @toto_32_ class                              *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto_32_ ;

//---------------------------------------------------------------------------*

class GALGAS_toto_32_ : public GALGAS_toto_31_ {
//--- Constructor
  public : GALGAS_toto_32_ (void) ;

//---
  public : inline const cPtr_toto_32_ * ptr (void) const { return (const cPtr_toto_32_ *) mObjectPtr ; }

//--------------------------------- Constructor from pointer
  public : GALGAS_toto_32_ (const cPtr_toto_32_ * inSourcePtr) ;



//-- Start of generic part --*

//--------------------------------- Object cloning
  protected : virtual AC_GALGAS_root * clonedObject (void) const ;

//--------------------------------- Object extraction
  public : static GALGAS_toto_32_ extractObject (const GALGAS_object & inObject,
                                                 C_Compiler * inCompiler,
                                                 const GALGAS_location & inErrorLocation
                                                 COMMA_LOCATION_ARGS) ;

//--------------------------------- Comparison
  public : typeComparisonResult objectCompare (const GALGAS_toto_32_ & inOperand) const ;

//--------------------------------- Modifiers

//--------------------------------- Instance Methods
//--------------------------------- Class Methods

//--------------------------------- Readers

//--------------------------------- Introspection
  public : VIRTUAL_IN_DEBUG const C_galgas_type_descriptor * staticTypeDescriptor (void) const ;
 
} ; // End of GALGAS_toto_32_ class


//---------------------------------------------------------------------------*

extern const C_galgas_type_descriptor kTypeDescriptor_GALGAS_toto_32_ ;

//---------------------------------------------------------------------------*
//                                                                           *
//                              @toto_33_ class                              *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto_33_ ;

//---------------------------------------------------------------------------*

class GALGAS_toto_33_ : public GALGAS_toto_32_ {
//--- Constructor
  public : GALGAS_toto_33_ (void) ;

//---
  public : inline const cPtr_toto_33_ * ptr (void) const { return (const cPtr_toto_33_ *) mObjectPtr ; }

//--------------------------------- Constructor from pointer
  public : GALGAS_toto_33_ (const cPtr_toto_33_ * inSourcePtr) ;



//-- Start of generic part --*

//--------------------------------- Object cloning
  protected : virtual AC_GALGAS_root * clonedObject (void) const ;

//--------------------------------- Object extraction
  public : static GALGAS_toto_33_ extractObject (const GALGAS_object & inObject,
                                                 C_Compiler * inCompiler,
                                                 const GALGAS_location & inErrorLocation
                                                 COMMA_LOCATION_ARGS) ;

//--------------------------------- GALGAS constructors
  public : static GALGAS_toto_33_ constructor_new (LOCATION_ARGS) ;

//--------------------------------- Comparison
  public : typeComparisonResult objectCompare (const GALGAS_toto_33_ & inOperand) const ;

//--------------------------------- Modifiers

//--------------------------------- Instance Methods
//--------------------------------- Class Methods

//--------------------------------- Readers

//--------------------------------- Introspection
  public : VIRTUAL_IN_DEBUG const C_galgas_type_descriptor * staticTypeDescriptor (void) const ;
 
} ; // End of GALGAS_toto_33_ class


//---------------------------------------------------------------------------*

extern const C_galgas_type_descriptor kTypeDescriptor_GALGAS_toto_33_ ;

//---------------------------------------------------------------------------*
//                                                                           *
//                        Category reader '@toto1 rr'                        *
//                                                                           *
//---------------------------------------------------------------------------*

typedef GALGAS_uint (*categoryReaderSignature_toto_31__rr) (const cPtr_toto_31_ * inObject,
                                                            C_Compiler * inCompiler
                                                            COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

void enterCategoryReader_rr (const PMSInt32 inClassIndex,
                             categoryReaderSignature_toto_31__rr inReader) ;

//---------------------------------------------------------------------------*

GALGAS_uint callCategoryReader_rr (const cPtr_toto_31_ * inObject,
                                   C_Compiler * inCompiler
                                   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                    Abstract category reader '@toto r'                     *
//                                                                           *
//---------------------------------------------------------------------------*

typedef GALGAS_uint (*categoryReaderSignature_toto_r) (const cPtr_toto * inObject,
                                                       C_Compiler * inCompiler
                                                       COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

void enterCategoryReader_r (const PMSInt32 inClassIndex,
                            categoryReaderSignature_toto_r inMethod) ;

//---------------------------------------------------------------------------*

GALGAS_uint callCategoryReader_r (const cPtr_toto * inObject,
                                  C_Compiler * inCompiler
                                  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//        Category method '@ipic18_instruction defineLabelAtAddress'         *
//                                                                           *
//---------------------------------------------------------------------------*

typedef void (*categoryMethodSignature_ipic_31__38__5F_instruction_defineLabelAtAddress) (const cPtr_ipic_31__38__5F_instruction * inObject,
                                                                                          GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & ioArgument0,
                                                                                          GALGAS_uint & ioArgument1,
                                                                                          C_Compiler * inCompiler
                                                                                          COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

void enterCategoryMethod_defineLabelAtAddress (const PMSInt32 inClassIndex,
                                               categoryMethodSignature_ipic_31__38__5F_instruction_defineLabelAtAddress inMethod) ;

//---------------------------------------------------------------------------*

void callCategoryMethod_defineLabelAtAddress (const cPtr_ipic_31__38__5F_instruction * inObject,
                                              GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives & io_ioRoutineSymbolTable,
                                              GALGAS_uint & io_ioAddress,
                                              C_Compiler * inCompiler
                                              COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//    Abstract category method '@ipic18_instruction checkRelativeBranch'     *
//                                                                           *
//---------------------------------------------------------------------------*

typedef void (*categoryMethodSignature_ipic_31__38__5F_instruction_checkRelativeBranch) (const cPtr_ipic_31__38__5F_instruction * inObject,
                                                                                         const GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives constinArgument0,
                                                                                         GALGAS_uint & ioArgument1,
                                                                                         GALGAS_bool & ioArgument2,
                                                                                         GALGAS_ipic_31__38__5F_instructionList & ioArgument3,
                                                                                         const GALGAS_uint constinArgument4,
                                                                                         GALGAS_string & ioArgument5,
                                                                                         C_Compiler * inCompiler
                                                                                         COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

void enterCategoryMethod_checkRelativeBranch (const PMSInt32 inClassIndex,
                                              categoryMethodSignature_ipic_31__38__5F_instruction_checkRelativeBranch inMethod) ;

//---------------------------------------------------------------------------*

void callCategoryMethod_checkRelativeBranch (const cPtr_ipic_31__38__5F_instruction * inObject,
                                             const GALGAS_ipic_31__38__5F_symbolTableForConvertingRelatives constin_inRoutineSymbolTable,
                                             GALGAS_uint & io_ioAddress,
                                             GALGAS_bool & io_ioRelativeBranchOverflow,
                                             GALGAS_ipic_31__38__5F_instructionList & io_ioGeneratedInstructionList,
                                             const GALGAS_uint constin_inIndex,
                                             GALGAS_string & io_ioListFileContents,
                                             C_Compiler * inCompiler
                                             COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//   Class for element of '@ipic18_symbolTableForConvertingRelatives' map    *
//                                                                           *
//---------------------------------------------------------------------------*

class cMapElement_ipic_31__38__5F_symbolTableForConvertingRelatives : public cMapElement {
//--- Map attributes
  public : GALGAS_uint mAttribute_mRoutineAddress ;

//--- Constructor
  public : cMapElement_ipic_31__38__5F_symbolTableForConvertingRelatives (const GALGAS_lstring & inKey,
                                                                          const GALGAS_uint & in_mRoutineAddress
                                                                          COMMA_LOCATION_ARGS) ;

//--- Virtual method for comparing elements
  public : virtual typeComparisonResult compare (const cCollectionElement * inOperand) const ;

//--- Virtual method that checks that all attributes are valid
  public : virtual bool isValid (void) const ;

//--- Virtual method that returns a copy of current object
  public : virtual cMapElement * copy (void) ;

//--- Description
 public : virtual void description (C_String & ioString, const PMSInt32 inIndentation) const ;
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Pointer class for @toto class                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto : public acPtr_class {

//--- Attributes

//--- Constructor
  public : cPtr_toto (LOCATION_ARGS) ;

} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                      Pointer class for @toto1 class                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto_31_ : public cPtr_toto {

//--- Attributes

//--- Constructor
  public : cPtr_toto_31_ (LOCATION_ARGS) ;
//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                      Pointer class for @toto2 class                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto_32_ : public cPtr_toto_31_ {

//--- Attributes

//--- Constructor
  public : cPtr_toto_32_ (LOCATION_ARGS) ;

} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                      Pointer class for @toto3 class                       *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_toto_33_ : public cPtr_toto_32_ {

//--- Attributes

//--- Constructor
  public : cPtr_toto_33_ (LOCATION_ARGS) ;
//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
