//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'ipic_optimizations.cpp'                        *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                      july 30th, 2008, at 16h21'46"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*

#include "version_libpm.h"
#if LIBPM_VERSION != THE_LIBPM_VERSION
  #error "This file has been compiled with a version of GALGAS different than the version of libpm"
#endif

//---------------------------------------------------------------------------*

#include <typeinfo>
#include "utilities/MF_MemoryControl.h"
#include "files/C_TextFileWrite.h"
#include "ipic_optimizations.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "ipic_optimizations.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                  class 'e_symbolTableForOptimizations'                    *
//                                                                           *
//---------------------------------------------------------------------------*

e_symbolTableForOptimizations::e_symbolTableForOptimizations (void) :
mDefinitionLineIndex () {
}

//---------------------------------------------------------------------------*
//                                                                           *
//                 class map '@symbolTableForOptimizations'                  *
//                                                                           *
//---------------------------------------------------------------------------*

elementOf_GGS_symbolTableForOptimizations::
elementOf_GGS_symbolTableForOptimizations (const GGS_lstring & inKey,
              const sint32 inIndex,
              const e_symbolTableForOptimizations & inInfo) :
AC_galgas_map_element (inKey, inIndex),
mInfo (inInfo) {
}

//---------------------------------------------------------------------------*

void elementOf_GGS_symbolTableForOptimizations::
appendForMapDescription (C_Compiler & _inLexique,
                         const sint32 inElementIndex,
                         C_String & ioString,
                         const sint32 inIndentation
                         COMMA_LOCATION_ARGS) const {
  ioString << "\n" ;
  ioString.writeStringMultiple ("| ", inIndentation) ;
  ioString << "|-key " << inElementIndex << ":" << mKey.reader_description  (_inLexique COMMA_THERE, inIndentation + 1) ;
  ioString << "\n" ;
  ioString.writeStringMultiple ("| ", inIndentation) ;
  ioString << "|-value " << inElementIndex << ":" << mInfo.mDefinitionLineIndex.reader_description  (_inLexique COMMA_THERE, inIndentation + 1) ;
}

//---------------------------------------------------------------------------*

bool elementOf_GGS_symbolTableForOptimizations::
isEqualToMapElement (const AC_galgas_map_element * inOperand) const {
  const elementOf_GGS_symbolTableForOptimizations * _p = dynamic_cast <const elementOf_GGS_symbolTableForOptimizations *> (inOperand) ;
  macroValidPointer (_p) ;
  return (mInfo.mDefinitionLineIndex._operator_isEqual (_p->mInfo.mDefinitionLineIndex)).boolValue () ;
}

//---------------------------------------------------------------------------*

AC_galgas_map_element * GGS_symbolTableForOptimizations::
new_element (const GGS_lstring & inKey, void * inInfo) {
  MF_Assert (reinterpret_cast <e_symbolTableForOptimizations *> (inInfo) != NULL, "Dynamic cast error", 0, 0) ;
  AC_galgas_map_element * p = NULL ;
  e_symbolTableForOptimizations * info = (e_symbolTableForOptimizations *) inInfo ;
  macroMyNew (p, cElement (inKey, nextIndex (), * info)) ;
  return p ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
assignInfo (AC_galgas_map_element * inPtr, void * inInfo) {
  MF_Assert (reinterpret_cast <cElement *> (inPtr) != NULL, "Dynamic cast error", 0, 0) ;
  MF_Assert (reinterpret_cast <e_symbolTableForOptimizations *> (inInfo) != NULL, "Dynamic cast error", 0, 0) ;
  cElement * p = (cElement *) inPtr ;
  e_symbolTableForOptimizations * info = (e_symbolTableForOptimizations *) inInfo ;
  p->mInfo = * info ;
}

//---------------------------------------------------------------------------*

GGS_symbolTableForOptimizations GGS_symbolTableForOptimizations::
constructor_emptyMap (C_Compiler & /* inLexique */ COMMA_UNUSED_LOCATION_ARGS) {
  GGS_symbolTableForOptimizations result ;
  macroMyNew (result.mSharedMapRoot, cMapRoot) ;
  return result ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
enterIndex (const GGS_lstring & inKey,
            AC_galgas_index_core & outIndex) {
  e_symbolTableForOptimizations info  ;
  internalEnterIndex (inKey,
                      (void *) & info,
                      mSharedMapRoot->_mRoot,
                      outIndex) ;
}

//---------------------------------------------------------------------------*

GGS_bool GGS_symbolTableForOptimizations::
_operator_isEqual (const GGS_symbolTableForOptimizations & inOperand) const {
  return GGS_bool (_isBuilt () && inOperand._isBuilt (), isEqualToMap (inOperand)) ;
}

//---------------------------------------------------------------------------*

GGS_bool GGS_symbolTableForOptimizations::
_operator_isNotEqual (const GGS_symbolTableForOptimizations & inOperand) const {
  return GGS_bool (_isBuilt () && inOperand._isBuilt (), ! isEqualToMap (inOperand)) ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
internalInsertForDuplication (AC_galgas_map_element * inPtr) {
  MF_Assert (reinterpret_cast <cElement *> (inPtr) != NULL, "Dynamic cast error", 0, 0) ;
  cElement * p = (cElement *) inPtr ;
  sint32 attributeIndex = -1 ; // Unused here
  GGS_location existingKeyLocation ; // Unused here
  internalInsert (p->mKey, (void *) & p->mInfo,mSharedMapRoot->_mRoot, attributeIndex, existingKeyLocation) ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
_removeElement (C_Compiler & inLexique,
                const char * inErrorMessage,
                const GGS_lstring & inKey,
                GGS_uint & outParameter0,
                GGS_luint * outIndex
                COMMA_LOCATION_ARGS) {
  AC_galgas_map_element * removedElement = NULL ;
  sint32 elementID = - 1 ;
  if (_isBuilt () && inKey._isBuilt ()) {
    insulateMap () ;
    bool unused ;
    _internalRemove (mSharedMapRoot->_mRoot, inKey, removedElement, unused) ;
    if (removedElement == NULL) {
      emitMapSemanticErrorMessage (inLexique, inKey, inErrorMessage COMMA_THERE) ;
      outParameter0._drop () ;
    }else{
      cElement * _p = (cElement *) removedElement ;
      elementID = _p->mID ;
      outParameter0 = _p->mInfo.mDefinitionLineIndex ;
    }
  }
  if (outIndex != NULL) {
    * outIndex = GGS_luint (GGS_uint (elementID >= 0, (uint32) elementID), inKey) ;
  }
  macroMyDelete (removedElement, cElement) ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
_insertElement (C_Compiler & inLexique,
                const char * inErrorMessage,
                const GGS_lstring & inKey,
                const GGS_uint & inParameter0,
                GGS_luint * outIndex
                COMMA_LOCATION_ARGS) {
  sint32 elementID = - 1 ;
  if (_isBuilt ()
   && inParameter0._isBuilt ()
   && inKey._isBuilt ()) {
    insulateMap () ;
    e_symbolTableForOptimizations info  ;
    info.mDefinitionLineIndex = inParameter0 ;
    GGS_location existingKeyLocation ;
    internalInsert (inKey, (void *) & info, mSharedMapRoot->_mRoot, elementID, existingKeyLocation) ;
    if (elementID < 0) {
      emitInsertMapSemanticErrorMessage (inLexique, inKey, inErrorMessage, existingKeyLocation COMMA_THERE) ;
    }
  }
  if (outIndex != NULL) {
    * outIndex = GGS_luint (GGS_uint (elementID >= 0, (uint32) elementID), inKey) ;
  }
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
_searchElement (C_Compiler & inLexique,
               const char * inErrorMessage,
               const GGS_lstring & inKey,
               GGS_uint   & outParameter0,
               GGS_luint * outIndex
               COMMA_LOCATION_ARGS) const {
  cElement * node = NULL  ;
  if (_isBuilt () && inKey._isBuilt ()) {
    AC_galgas_map_element * p = internal_search (inKey) ;
    MF_Assert ((p == NULL) || (reinterpret_cast <cElement *> (p) != NULL), "Dynamic cast error", 0, 0) ;
    node = (cElement *) p ;
    if (node == NULL) {
      emitMapSemanticErrorMessage (inLexique, inKey, inErrorMessage COMMA_THERE) ;
    }
  }
  if (node == NULL) {
    outParameter0._drop () ;
    if (outIndex != NULL) {
      outIndex->_drop () ;
     }
  }else{
    outParameter0 = node->mInfo.mDefinitionLineIndex ;
    if (outIndex != NULL) {
      * outIndex = GGS_luint (GGS_uint (true, (uint32) node->mID), inKey) ;
    }
  }
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
modifier_setMDefinitionLineIndexForKey (C_Compiler & inLexique,
                        const GGS_uint & inValue,
                        const GGS_string & inKey
                        COMMA_LOCATION_ARGS) {
  if (_isBuilt () && inValue._isBuilt () && inKey._isBuilt ()) {
    insulateMap () ;
    AC_galgas_map_element * p = internal_search (inKey) ;
    MF_Assert ((p == NULL) || (reinterpret_cast <cElement *> (p) != NULL), "Dynamic cast error", 0, 0) ;
    cElement * node = (cElement *) p ;
    if (node == NULL) {
      C_String errorMessage ;
      errorMessage << "the '" << inKey << "' key does not exist when calling 'setMDefinitionLineIndexForKey' modifier" ;
      inLexique.onTheFlyRunTimeError (errorMessage COMMA_THERE) ;
    }else{
      node->mInfo.mDefinitionLineIndex = inValue ;
    }
  }
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
method_searchKey (C_Compiler & inLexique,
                                const GGS_lstring & inKey,
                                GGS_uint   & outParameter0 COMMA_LOCATION_ARGS) const {
  _searchElement (inLexique,
                  "the '%K' label is not declared",
                  inKey,
                  outParameter0,
                  NULL
                  COMMA_THERE) ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
modifier_removeKey (C_Compiler & _inLexique,
                                const GGS_lstring & inKey,
                                GGS_uint & outParameter0 COMMA_LOCATION_ARGS) {
  _removeElement (_inLexique,
                  "the '%K' label is not declared",
                  inKey,
                  outParameter0,
                  NULL
                  COMMA_THERE) ;
}

//---------------------------------------------------------------------------*

void GGS_symbolTableForOptimizations::
modifier_insertKey (C_Compiler & _inLexique,
                                const GGS_lstring & inKey,
                                const GGS_uint & inParameter0 COMMA_LOCATION_ARGS) {
  _insertElement (_inLexique,
                 "the '%K' label is already declared in %L",
                 inKey,
                 inParameter0,
                 NULL
                 COMMA_THERE) ;
}

//---------------------------------------------------------------------------*

GGS_symbolTableForOptimizations GGS_symbolTableForOptimizations::
constructor_mapWithMapToOverride (C_Compiler & /* inLexique */,
                                  const GGS_symbolTableForOptimizations & inMapToOverride
                                  COMMA_UNUSED_LOCATION_ARGS) {
  GGS_symbolTableForOptimizations result ; // Not Built
  if (inMapToOverride.mSharedMapRoot != NULL) {
    macroValidPointer (inMapToOverride.mSharedMapRoot) ;
    macroMyNew (result.mSharedMapRoot, cMapRoot) ;
    result.mSharedMapRoot->mNextMap = inMapToOverride.mSharedMapRoot ;
    inMapToOverride.mSharedMapRoot->mReferenceCount ++ ;
    result.mSharedMapRoot->mSequenceNumber = inMapToOverride.mSharedMapRoot->mSequenceNumber ;
  }
  return result ;
}

//---------------------------------------------------------------------------*

GGS_symbolTableForOptimizations GGS_symbolTableForOptimizations::
reader_overriddenMap (C_Compiler & /* inLexique */
                      COMMA_UNUSED_LOCATION_ARGS) const {
  GGS_symbolTableForOptimizations result ; // Not Built
  if (mSharedMapRoot != NULL) {
    macroValidPointer (mSharedMapRoot) ;
    result.mSharedMapRoot = mSharedMapRoot->mNextMap ;
    if (result.mSharedMapRoot != NULL) {
      macroValidPointer (result.mSharedMapRoot) ;
      result.mSharedMapRoot->mReferenceCount ++ ;
    }else{
      macroMyNew (result.mSharedMapRoot, cMapRoot) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*

GGS_string GGS_symbolTableForOptimizations::
reader_description (C_Compiler & _inLexique
                    COMMA_LOCATION_ARGS,
                    const sint32 inIndentation) const {
  C_String s ;
  s << "<map @symbolTableForOptimizations " ;
  if (_isBuilt ()) {
    s << count () << " object" << ((count () > 1) ? "s " : " ") ;
    cElement * p = firstObject () ;
    sint32 elementID = 0 ;
    while (p != NULL) {
      macroValidPointer (p) ;
      p->appendForMapDescription (_inLexique, elementID, s, inIndentation COMMA_THERE) ;
      p = p->nextObject () ;
      elementID ++ ;
    }
  }else{
    s << "not built" ;
  }
  s << "\n" ;
  s.writeStringMultiple ("| ", inIndentation) ;
  s << ">" ;
  return GGS_string (true, s) ;
}

//---------------------------------------------------------------------------*

/* const */ GGS_uint  & GGS_symbolTableForOptimizations::cEnumerator::_mDefinitionLineIndex (LOCATION_ARGS) const {
  return ((cElement *) mObjectArray (mCurrentIndex COMMA_THERE))->mInfo.mDefinitionLineIndex ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             Category method '@ipic_instruction.defineLabel'               *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_instruction__defineLabel (C_Compiler &,
                                const cPtr_ipic_instruction * operand_978,
                                GGS_symbolTableForOptimizations  & /* var_cas_ioRoutineSymbolTable */,
                                const GGS_uint   /* var_cas_inLineIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_978 != NULL) {
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Virtual Table for category method '@ipic_instruction.defineLabel'      *
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_instruction__defineLabel> gDispatchTableFor__ipic_instruction__defineLabel ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_instruction__defineLabel (typeCategoryMethod__ipic_instruction__defineLabel inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_instruction__defineLabel.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_instruction__defineLabel
findCategoryMethod__ipic_instruction__defineLabel (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_instruction__defineLabel result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_instruction__defineLabel.count ()) {
    result = gDispatchTableFor__ipic_instruction__defineLabel (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_instruction__defineLabel (superClassPtr) ;
      gDispatchTableFor__ipic_instruction__defineLabel.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             Category method '@ipic_pseudo_LABEL.defineLabel'              *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_pseudo_LABEL__defineLabel (C_Compiler & _inLexique,
                                const cPtr_ipic_pseudo_LABEL * operand_1212,
                                GGS_symbolTableForOptimizations  & var_cas_ioRoutineSymbolTable,
                                const GGS_uint   var_cas_inLineIndex
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_1212 != NULL) {
    var_cas_ioRoutineSymbolTable.modifier_insertKey (_inLexique, operand_1212->mLabel, var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (34)) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//       Implementation of routine "findFirstInstructionFromAddress"         *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_findFirstInstructionFromAddress (C_Compiler & _inLexique,
                                const GGS_uint   var_cas_inLineIndex,
                                const GGS_ipic_instructionList   var_cas_inGeneratedInstructionList,
                                GGS_ipic_instruction  & var_cas_outFirstInstruction COMMA_UNUSED_LOCATION_ARGS) {
  #ifdef DEBUG_TRACE_ENABLED
    printf ("ENTER routine_findFirstInstructionFromAddress at %s:%d\n", __FILE__, __LINE__) ;
  #endif
  GGS_uint  var_cas_currentLineIndex ;
  var_cas_currentLineIndex = var_cas_inLineIndex ;
  var_cas_outFirstInstruction = GGS_ipic_NULL ::constructor_new (_inLexique COMMA_HERE) ;
  GGS_bool var_cas_found ;
  var_cas_found = GGS_bool (true, false) ;
  GGS_uint _variant_2167 = var_cas_inGeneratedInstructionList.reader_length (_inLexique COMMA_SOURCE_FILE_AT_LINE (49)) ;
  GGS_bool _condition_2167 (_variant_2167._isBuilt (), true) ;
  while (_condition_2167.isBuiltAndTrue ()) {
    _condition_2167 = ((var_cas_currentLineIndex)._operator_strictInf (var_cas_inGeneratedInstructionList.reader_length (_inLexique COMMA_SOURCE_FILE_AT_LINE (50))))._operator_and ((var_cas_found)._operator_not ()) ;
    if (_condition_2167.isBuiltAndTrue ()) {
      if (_variant_2167.uintValue () == 0) {
        _inLexique.onTheFlyRunTimeError ("loop variant error" COMMA_SOURCE_FILE_AT_LINE (58)) ;
        _condition_2167 = GGS_bool (true, false) ;
      }else{
        _variant_2167._decrement_operation (_inLexique COMMA_HERE) ;
        { const GGS_ipic_instruction _var_2126 = var_cas_inGeneratedInstructionList.reader_mInstructionAtIndex (_inLexique, var_cas_currentLineIndex COMMA_SOURCE_FILE_AT_LINE (52)) ; // CAST instruction
          if (_var_2126.getPtr () != NULL) {
            macroValidPointer (_var_2126.getPtr ()) ;
            if (dynamic_cast <cPtr_ipic_actualInstruction *> (_var_2126.getPtr ()) != NULL) {
              const GGS_ipic_actualInstruction var_cas_instr (_var_2126.getPtr ()) ;
              var_cas_outFirstInstruction = var_cas_instr ;
              var_cas_found = GGS_bool (true, true) ;
            }else{
            }
          }
        }
        var_cas_currentLineIndex._increment_operation (_inLexique COMMA_SOURCE_FILE_AT_LINE (58)) ;
      }
    }
  }
  #ifdef DEBUG_TRACE_ENABLED
    printf ("LEAVE routine_findFirstInstructionFromAddress\n") ;
  #endif
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Implementation of routine "findFirstInstructionOrLabelFromAddress"     *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_findFirstInstructionOrLabelFromAddress (C_Compiler & _inLexique,
                                const GGS_uint   var_cas_inLineIndex,
                                const GGS_ipic_instructionList   var_cas_inGeneratedInstructionList,
                                GGS_ipic_instruction  & var_cas_outFirstInstruction COMMA_UNUSED_LOCATION_ARGS) {
  #ifdef DEBUG_TRACE_ENABLED
    printf ("ENTER routine_findFirstInstructionOrLabelFromAddress at %s:%d\n", __FILE__, __LINE__) ;
  #endif
  GGS_uint  var_cas_currentLineIndex ;
  var_cas_currentLineIndex = var_cas_inLineIndex ;
  var_cas_outFirstInstruction = GGS_ipic_NULL ::constructor_new (_inLexique COMMA_HERE) ;
  GGS_bool var_cas_found ;
  var_cas_found = GGS_bool (true, false) ;
  GGS_uint _variant_3093 = var_cas_inGeneratedInstructionList.reader_length (_inLexique COMMA_SOURCE_FILE_AT_LINE (74)) ;
  GGS_bool _condition_3093 (_variant_3093._isBuilt (), true) ;
  while (_condition_3093.isBuiltAndTrue ()) {
    _condition_3093 = ((var_cas_currentLineIndex)._operator_strictInf (var_cas_inGeneratedInstructionList.reader_length (_inLexique COMMA_SOURCE_FILE_AT_LINE (75))))._operator_and ((var_cas_found)._operator_not ()) ;
    if (_condition_3093.isBuiltAndTrue ()) {
      if (_variant_3093.uintValue () == 0) {
        _inLexique.onTheFlyRunTimeError ("loop variant error" COMMA_SOURCE_FILE_AT_LINE (86)) ;
        _condition_3093 = GGS_bool (true, false) ;
      }else{
        _variant_3093._decrement_operation (_inLexique COMMA_HERE) ;
        { const GGS_ipic_instruction _var_3052 = var_cas_inGeneratedInstructionList.reader_mInstructionAtIndex (_inLexique, var_cas_currentLineIndex COMMA_SOURCE_FILE_AT_LINE (77)) ; // CAST instruction
          if (_var_3052.getPtr () != NULL) {
            macroValidPointer (_var_3052.getPtr ()) ;
            if (dynamic_cast <cPtr_ipic_actualInstruction *> (_var_3052.getPtr ()) != NULL) {
              const GGS_ipic_actualInstruction var_cas_instr (_var_3052.getPtr ()) ;
              var_cas_outFirstInstruction = var_cas_instr ;
              var_cas_found = GGS_bool (true, true) ;
            }else if (typeid (cPtr_ipic_pseudo_LABEL) == typeid (* (_var_3052.getPtr ()))) {
              const GGS_ipic_pseudo_LABEL var_cas_instr (_var_3052.getPtr ()) ;
              var_cas_outFirstInstruction = var_cas_instr ;
              var_cas_found = GGS_bool (true, true) ;
            }else{
            }
          }
        }
        var_cas_currentLineIndex._increment_operation (_inLexique COMMA_SOURCE_FILE_AT_LINE (86)) ;
      }
    }
  }
  #ifdef DEBUG_TRACE_ENABLED
    printf ("LEAVE routine_findFirstInstructionOrLabelFromAddress\n") ;
  #endif
}

//---------------------------------------------------------------------------*
//                                                                           *
//                Category method '@ipic_JUMP.optimizeJUMP'                  *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_JUMP__optimizeJUMP (C_Compiler & _inLexique,
                                const cPtr_ipic_JUMP * operand_3536,
                                const GGS_symbolTableForOptimizations   var_cas_inSymbolTable,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_3536 != NULL) {
    GGS_uint  var_cas_line ;
    const GGS_symbolTableForOptimizations  _temp_3807 = var_cas_inSymbolTable ;
    if (_temp_3807._isBuilt ()) {
      _temp_3807 (HERE)->method_searchKey (_inLexique, operand_3536->mTargetLabel, var_cas_line COMMA_SOURCE_FILE_AT_LINE (104)) ;
    }
    GGS_ipic_instruction  var_cas_firstInstruction ;
    ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_line._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (107)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (106)) ;
    { const GGS_ipic_instruction _var_5534 = var_cas_firstInstruction ; // CAST instruction
      if (_var_5534.getPtr () != NULL) {
        macroValidPointer (_var_5534.getPtr ()) ;
        if (typeid (cPtr_ipic_instruction_RETURN) == typeid (* (_var_5534.getPtr ()))) {
          var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_instruction_RETURN ::constructor_new (_inLexique, operand_3536->mInstructionLocation COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (111)) ;
          var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
          if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (116)))).isBuiltAndTrue ()) {
            var_cas_ioListFileContents.writeString ("  line ") ;
            var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (117))) ;
            var_cas_ioListFileContents.writeString (": JUMP branching to RETURN replaced by RETURN\n") ;
          }
        }else if (typeid (cPtr_ipic_JUMP) == typeid (* (_var_5534.getPtr ()))) {
          const GGS_ipic_JUMP var_cas_jump (_var_5534.getPtr ()) ;
          if (((operand_3536->mTargetLabel)._operator_isNotEqual (var_cas_jump.reader_mTargetLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (120)))).isBuiltAndTrue ()) {
            var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_JUMP ::constructor_new (_inLexique, operand_3536->mInstructionLocation, var_cas_jump.reader_mTargetLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (122)), operand_3536->mKind COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (121)) ;
            var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
            if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (126)))).isBuiltAndTrue ()) {
              var_cas_ioListFileContents.writeString ("  line ") ;
              var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (127))) ;
              var_cas_ioListFileContents.writeString (": JUMP branching to JUMP replaced by JUMP\n") ;
            }
          }
        }else{
          GGS_ipic_instruction  var_cas_nextInstruction ;
          ::routine_findFirstInstructionOrLabelFromAddress (_inLexique,  var_cas_inLineIndex._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (132)),  var_cas_ioGeneratedInstructionList,  var_cas_nextInstruction COMMA_SOURCE_FILE_AT_LINE (131)) ;
          { const GGS_ipic_instruction _var_5519 = var_cas_nextInstruction ; // CAST instruction
            if (_var_5519.getPtr () != NULL) {
              macroValidPointer (_var_5519.getPtr ()) ;
              if (typeid (cPtr_ipic_pseudo_LABEL) == typeid (* (_var_5519.getPtr ()))) {
                const GGS_ipic_pseudo_LABEL var_cas_instr (_var_5519.getPtr ()) ;
                if (((var_cas_instr.reader_mLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (135)).reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (135)))._operator_isEqual (operand_3536->mTargetLabel.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (135)))).isBuiltAndTrue ()) {
                  var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_NULL ::constructor_new (_inLexique COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (136)) ;
                  var_cas_ioListFileContents.writeString ("  line ") ;
                  var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (137))) ;
                  var_cas_ioListFileContents.writeString (": JUMP branching to next instruction deleted\n") ;
                }
              }else{
              }
            }
          }
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//       Virtual Table for category method '@ipic_JUMP.optimizeJUMP'         *
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_JUMP__optimizeJUMP> gDispatchTableFor__ipic_JUMP__optimizeJUMP ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_JUMP__optimizeJUMP (typeCategoryMethod__ipic_JUMP__optimizeJUMP inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_JUMP__optimizeJUMP.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_JUMP__optimizeJUMP
findCategoryMethod__ipic_JUMP__optimizeJUMP (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_JUMP__optimizeJUMP result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_JUMP__optimizeJUMP.count ()) {
    result = gDispatchTableFor__ipic_JUMP__optimizeJUMP (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_JUMP__optimizeJUMP (superClassPtr) ;
      gDispatchTableFor__ipic_JUMP__optimizeJUMP.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                 Category method '@ipic_JSR.optimizeJSR'                   *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_JSR__optimizeJSR (C_Compiler & _inLexique,
                                const cPtr_ipic_JSR * operand_5659,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_5659 != NULL) {
    GGS_ipic_instruction  var_cas_firstInstruction ;
    ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_inLineIndex._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (154)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (153)) ;
    { const GGS_ipic_instruction _var_6463 = var_cas_firstInstruction ; // CAST instruction
      if (_var_6463.getPtr () != NULL) {
        macroValidPointer (_var_6463.getPtr ()) ;
        if (typeid (cPtr_ipic_instruction_RETURN) == typeid (* (_var_6463.getPtr ()))) {
          var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_JUMP ::constructor_new (_inLexique, operand_5659->mInstructionLocation, operand_5659->mTargetLabel, operand_5659->mKind COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (158)) ;
          var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
          if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (163)))).isBuiltAndTrue ()) {
            var_cas_ioListFileContents.writeString ("  line ") ;
            var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (164))) ;
            var_cas_ioListFileContents.writeString (": JSR followed by RETURN replaced by JUMP\n") ;
          }
        }else{
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//        Virtual Table for category method '@ipic_JSR.optimizeJSR'          *
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_JSR__optimizeJSR> gDispatchTableFor__ipic_JSR__optimizeJSR ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_JSR__optimizeJSR (typeCategoryMethod__ipic_JSR__optimizeJSR inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_JSR__optimizeJSR.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_JSR__optimizeJSR
findCategoryMethod__ipic_JSR__optimizeJSR (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_JSR__optimizeJSR result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_JSR__optimizeJSR.count ()) {
    result = gDispatchTableFor__ipic_JSR__optimizeJSR (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_JSR__optimizeJSR (superClassPtr) ;
      gDispatchTableFor__ipic_JSR__optimizeJSR.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Category method '@ipic_instruction_literalOperation.optimizeMOVLW'     *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_instruction_literalOperation__optimizeMOVLW (C_Compiler & _inLexique,
                                const cPtr_ipic_instruction_literalOperation * operand_6613,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6613 != NULL) {
    if (((operand_6613->mLiteralInstruction)._operator_isEqual (GGS_literal_instruction_opcode::constructor_MOVLW (_inLexique COMMA_HERE))).isBuiltAndTrue ()) {
      GGS_ipic_instruction  var_cas_firstInstruction ;
      ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_inLineIndex._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (181)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (180)) ;
      { const GGS_ipic_instruction _var_7576 = var_cas_firstInstruction ; // CAST instruction
        if (_var_7576.getPtr () != NULL) {
          macroValidPointer (_var_7576.getPtr ()) ;
          if (typeid (cPtr_ipic_instruction_RETURN) == typeid (* (_var_7576.getPtr ()))) {
            var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_instruction_literalOperation ::constructor_new (_inLexique, operand_6613->mInstructionLocation, GGS_literal_instruction_opcode::constructor_RETLW (_inLexique COMMA_HERE), operand_6613->mLiteralValue COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (185)) ;
            var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
            if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (190)))).isBuiltAndTrue ()) {
              var_cas_ioListFileContents.writeString ("  line ") ;
              var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (191))) ;
              var_cas_ioListFileContents.writeString (": MOVLW followed by RETURN replaced by RETLW\n") ;
            }
          }else{
          }
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@ipic_instruction_literalOperation.optimizeMOVLW'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW> gDispatchTableFor__ipic_instruction_literalOperation__optimizeMOVLW ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW (typeCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_instruction_literalOperation__optimizeMOVLW.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW
findCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_instruction_literalOperation__optimizeMOVLW.count ()) {
    result = gDispatchTableFor__ipic_instruction_literalOperation__optimizeMOVLW (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW (superClassPtr) ;
      gDispatchTableFor__ipic_instruction_literalOperation__optimizeMOVLW.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Category method '@ipic_instruction_conditionalBranch.optimizeBCC'      *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_instruction_conditionalBranch__optimizeBCC (C_Compiler & _inLexique,
                                const cPtr_ipic_instruction_conditionalBranch * operand_7740,
                                const GGS_symbolTableForOptimizations   var_cas_inSymbolTable,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_7740 != NULL) {
    GGS_uint  var_cas_line ;
    const GGS_symbolTableForOptimizations  _temp_8010 = var_cas_inSymbolTable ;
    if (_temp_8010._isBuilt ()) {
      _temp_8010 (HERE)->method_searchKey (_inLexique, operand_7740->mTargetLabel, var_cas_line COMMA_SOURCE_FILE_AT_LINE (208)) ;
    }
    GGS_ipic_instruction  var_cas_firstInstruction ;
    ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_line._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (211)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (210)) ;
    { const GGS_ipic_instruction _var_8801 = var_cas_firstInstruction ; // CAST instruction
      if (_var_8801.getPtr () != NULL) {
        macroValidPointer (_var_8801.getPtr ()) ;
        if (typeid (cPtr_ipic_JUMP) == typeid (* (_var_8801.getPtr ()))) {
          const GGS_ipic_JUMP var_cas_jump (_var_8801.getPtr ()) ;
          var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_instruction_conditionalBranch ::constructor_new (_inLexique, operand_7740->mInstructionLocation, operand_7740->mBranchMode, operand_7740->mConditionalBranch, var_cas_jump.reader_mTargetLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (216)) COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (215)) ;
          var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
          if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (220)))).isBuiltAndTrue ()) {
            var_cas_ioListFileContents.writeString ("  line ") ;
            var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (221))) ;
            var_cas_ioListFileContents.writeString (": label of JUMP ") ;
            var_cas_ioListFileContents._dotAssign_operation (operand_7740->mConditionalBranch.reader_condition (_inLexique COMMA_SOURCE_FILE_AT_LINE (221))) ;
            var_cas_ioListFileContents.writeString (" branching to JUMP replaced by second JUMP label\n") ;
          }
        }else{
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@ipic_instruction_conditionalBranch.optimizeBCC'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC> gDispatchTableFor__ipic_instruction_conditionalBranch__optimizeBCC ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC (typeCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_instruction_conditionalBranch__optimizeBCC.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC
findCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_instruction_conditionalBranch__optimizeBCC.count ()) {
    result = gDispatchTableFor__ipic_instruction_conditionalBranch__optimizeBCC (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC (superClassPtr) ;
      gDispatchTableFor__ipic_instruction_conditionalBranch__optimizeBCC.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        Category method '@ipic_jump_test_register.optimizeTestReg'         *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_jump_test_register__optimizeTestReg (C_Compiler & _inLexique,
                                const cPtr_ipic_jump_test_register * operand_8941,
                                const GGS_symbolTableForOptimizations   var_cas_inSymbolTable,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_8941 != NULL) {
    GGS_uint  var_cas_line ;
    const GGS_symbolTableForOptimizations  _temp_9215 = var_cas_inSymbolTable ;
    if (_temp_9215._isBuilt ()) {
      _temp_9215 (HERE)->method_searchKey (_inLexique, GGS_lstring ::constructor_new (_inLexique, operand_8941->mTargetLabel, GGS_location (_inLexique) COMMA_HERE), var_cas_line COMMA_SOURCE_FILE_AT_LINE (237)) ;
    }
    GGS_ipic_instruction  var_cas_firstInstruction ;
    ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_line._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (240)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (239)) ;
    { const GGS_ipic_instruction _var_10203 = var_cas_firstInstruction ; // CAST instruction
      if (_var_10203.getPtr () != NULL) {
        macroValidPointer (_var_10203.getPtr ()) ;
        if (typeid (cPtr_ipic_JUMP) == typeid (* (_var_10203.getPtr ()))) {
          const GGS_ipic_JUMP var_cas_jump (_var_10203.getPtr ()) ;
          var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_jump_test_register ::constructor_new (_inLexique, operand_8941->mInstructionLocation, operand_8941->mRegisterDescription, var_cas_jump.reader_mTargetLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (245)).reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (245)), operand_8941->mBranchIfZero, operand_8941->mUsesBra COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (244)) ;
          var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
          if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (249)))).isBuiltAndTrue ()) {
            var_cas_ioListFileContents.writeString ("  line ") ;
            var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (250))) ;
            var_cas_ioListFileContents.writeString (": label of JUMP ") ;
            var_cas_ioListFileContents._dotAssign_operation (operand_8941->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (250))) ;
            if ((operand_8941->mBranchIfZero).isBuiltAndTrue ()) {
              var_cas_ioListFileContents.writeString ("Z") ;
            }else{
              var_cas_ioListFileContents.writeString ("NZ") ;
            }
            var_cas_ioListFileContents.writeString (" branching to JUMP replaced by second JUMP label\n") ;
          }
        }else{
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@ipic_jump_test_register.optimizeTestReg'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_jump_test_register__optimizeTestReg> gDispatchTableFor__ipic_jump_test_register__optimizeTestReg ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_jump_test_register__optimizeTestReg (typeCategoryMethod__ipic_jump_test_register__optimizeTestReg inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_jump_test_register__optimizeTestReg.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_jump_test_register__optimizeTestReg
findCategoryMethod__ipic_jump_test_register__optimizeTestReg (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_jump_test_register__optimizeTestReg result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_jump_test_register__optimizeTestReg.count ()) {
    result = gDispatchTableFor__ipic_jump_test_register__optimizeTestReg (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_jump_test_register__optimizeTestReg (superClassPtr) ;
      gDispatchTableFor__ipic_jump_test_register__optimizeTestReg.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//   Category method '@ipic_incDecRegisterInCondition.optimizeTestDecInc'    *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_incDecRegisterInCondition__optimizeTestDecInc (C_Compiler & _inLexique,
                                const cPtr_ipic_incDecRegisterInCondition * operand_10350,
                                const GGS_symbolTableForOptimizations   var_cas_inSymbolTable,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_10350 != NULL) {
    GGS_uint  var_cas_line ;
    const GGS_symbolTableForOptimizations  _temp_10627 = var_cas_inSymbolTable ;
    if (_temp_10627._isBuilt ()) {
      _temp_10627 (HERE)->method_searchKey (_inLexique, GGS_lstring ::constructor_new (_inLexique, operand_10350->mTargetLabel, GGS_location (_inLexique) COMMA_HERE), var_cas_line COMMA_SOURCE_FILE_AT_LINE (272)) ;
    }
    GGS_ipic_instruction  var_cas_firstInstruction ;
    ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_line._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (275)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (274)) ;
    { const GGS_ipic_instruction _var_11994 = var_cas_firstInstruction ; // CAST instruction
      if (_var_11994.getPtr () != NULL) {
        macroValidPointer (_var_11994.getPtr ()) ;
        if (typeid (cPtr_ipic_JUMP) == typeid (* (_var_11994.getPtr ()))) {
          const GGS_ipic_JUMP var_cas_jump (_var_11994.getPtr ()) ;
          var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_incDecRegisterInCondition ::constructor_new (_inLexique, operand_10350->mInstructionLocation, operand_10350->mRegisterDescription, var_cas_jump.reader_mTargetLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (283)).reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (283)), operand_10350->mIncrement, operand_10350->m_W_isDestination, operand_10350->mBranchIfZero, operand_10350->mUsesBra COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (279)) ;
          var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
          if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (292)))).isBuiltAndTrue ()) {
            var_cas_ioListFileContents.writeString ("  line ") ;
            var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (293))) ;
            var_cas_ioListFileContents.writeString (": label of ") ;
            var_cas_ioListFileContents.writeString ("JUMP ") ;
            if ((operand_10350->mIncrement).isBuiltAndTrue ()) {
              var_cas_ioListFileContents.writeString ("INCF ") ;
            }else{
              var_cas_ioListFileContents.writeString ("DECF ") ;
            }
            var_cas_ioListFileContents._dotAssign_operation (operand_10350->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (300))) ;
            if ((operand_10350->m_W_isDestination).isBuiltAndTrue ()) {
              var_cas_ioListFileContents.writeString (", W ") ;
            }
            if ((operand_10350->mBranchIfZero).isBuiltAndTrue ()) {
              var_cas_ioListFileContents.writeString ("Z") ;
            }else{
              var_cas_ioListFileContents.writeString ("NZ") ;
            }
            var_cas_ioListFileContents.writeString (" branching to JUMP replaced by second JUMP label\n") ;
          }
        }else{
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@ipic_incDecRegisterInCondition.optimizeTestDecInc'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc> gDispatchTableFor__ipic_incDecRegisterInCondition__optimizeTestDecInc ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc (typeCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_incDecRegisterInCondition__optimizeTestDecInc.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc
findCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_incDecRegisterInCondition__optimizeTestDecInc.count ()) {
    result = gDispatchTableFor__ipic_incDecRegisterInCondition__optimizeTestDecInc (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc (superClassPtr) ;
      gDispatchTableFor__ipic_incDecRegisterInCondition__optimizeTestDecInc.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     Category method '@ipic_registerComparisonCondition.optimizeCMP'       *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__ipic_registerComparisonCondition__optimizeCMP (C_Compiler & _inLexique,
                                const cPtr_ipic_registerComparisonCondition * operand_12143,
                                const GGS_symbolTableForOptimizations   var_cas_inSymbolTable,
                                const GGS_uint   var_cas_inLineIndex,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents,
                                GGS_bool & var_cas_ioOptimizationsDone
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_12143 != NULL) {
    GGS_uint  var_cas_line ;
    const GGS_symbolTableForOptimizations  _temp_12413 = var_cas_inSymbolTable ;
    if (_temp_12413._isBuilt ()) {
      _temp_12413 (HERE)->method_searchKey (_inLexique, GGS_lstring ::constructor_new (_inLexique, operand_12143->mTargetLabel, GGS_location (_inLexique) COMMA_HERE), var_cas_line COMMA_SOURCE_FILE_AT_LINE (325)) ;
    }
    GGS_ipic_instruction  var_cas_firstInstruction ;
    ::routine_findFirstInstructionFromAddress (_inLexique,  var_cas_line._add_operation (_inLexique, GGS_uint (true, 1U) COMMA_SOURCE_FILE_AT_LINE (328)),  var_cas_ioGeneratedInstructionList,  var_cas_firstInstruction COMMA_SOURCE_FILE_AT_LINE (327)) ;
    { const GGS_ipic_instruction _var_13448 = var_cas_firstInstruction ; // CAST instruction
      if (_var_13448.getPtr () != NULL) {
        macroValidPointer (_var_13448.getPtr ()) ;
        if (typeid (cPtr_ipic_JUMP) == typeid (* (_var_13448.getPtr ()))) {
          const GGS_ipic_JUMP var_cas_jump (_var_13448.getPtr ()) ;
          var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_registerComparisonCondition ::constructor_new (_inLexique, operand_12143->mInstructionLocation, operand_12143->mRegisterDescription, var_cas_jump.reader_mTargetLabel (_inLexique COMMA_SOURCE_FILE_AT_LINE (336)).reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (336)), operand_12143->mComparison, operand_12143->mUsesBra COMMA_HERE), var_cas_inLineIndex COMMA_SOURCE_FILE_AT_LINE (332)) ;
          var_cas_ioOptimizationsDone = GGS_bool (true, true) ;
          if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (343)))).isBuiltAndTrue ()) {
            var_cas_ioListFileContents.writeString ("  line ") ;
            var_cas_ioListFileContents._dotAssign_operation (var_cas_inLineIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (344))) ;
            var_cas_ioListFileContents.writeString (": label of ") ;
            var_cas_ioListFileContents.writeString ("JUMP ") ;
            var_cas_ioListFileContents._dotAssign_operation (operand_12143->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (346))) ;
            var_cas_ioListFileContents.writeString (" ") ;
            var_cas_ioListFileContents._dotAssign_operation (operand_12143->mComparison.reader_mnemonic (_inLexique COMMA_SOURCE_FILE_AT_LINE (347))) ;
            var_cas_ioListFileContents.writeString (" branching to JUMP replaced by second JUMP label\n") ;
          }
        }else{
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@ipic_registerComparisonCondition.optimizeCMP'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__ipic_registerComparisonCondition__optimizeCMP> gDispatchTableFor__ipic_registerComparisonCondition__optimizeCMP ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__ipic_registerComparisonCondition__optimizeCMP (typeCategoryMethod__ipic_registerComparisonCondition__optimizeCMP inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__ipic_registerComparisonCondition__optimizeCMP.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__ipic_registerComparisonCondition__optimizeCMP
findCategoryMethod__ipic_registerComparisonCondition__optimizeCMP (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__ipic_registerComparisonCondition__optimizeCMP result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__ipic_registerComparisonCondition__optimizeCMP.count ()) {
    result = gDispatchTableFor__ipic_registerComparisonCondition__optimizeCMP (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__ipic_registerComparisonCondition__optimizeCMP (superClassPtr) ;
      gDispatchTableFor__ipic_registerComparisonCondition__optimizeCMP.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             Implementation of routine "performOptimizations"              *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_performOptimizations (C_Compiler & _inLexique,
                                GGS_ipic_instructionList  & var_cas_ioGeneratedInstructionList,
                                GGS_string & var_cas_ioListFileContents COMMA_UNUSED_LOCATION_ARGS) {
  #ifdef DEBUG_TRACE_ENABLED
    printf ("ENTER routine_performOptimizations at %s:%d\n", __FILE__, __LINE__) ;
  #endif
  if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (365)))).isBuiltAndTrue ()) {
    var_cas_ioListFileContents._dotAssign_operation (GGS_string (true, "").reader_stringByLeftAndRightPadding (_inLexique, GGS_uint (true, 79U), GGS_char (true, '*') COMMA_SOURCE_FILE_AT_LINE (366))) ;
    var_cas_ioListFileContents.writeString ("\n") ;
    var_cas_ioListFileContents.writeString ("*") ;
    var_cas_ioListFileContents._dotAssign_operation (GGS_string (true, "CODE OPTIMIZATION").reader_stringByLeftAndRightPadding (_inLexique, GGS_uint (true, 77U), GGS_char (true, ' ') COMMA_SOURCE_FILE_AT_LINE (367))) ;
    var_cas_ioListFileContents.writeString ("*\n") ;
    var_cas_ioListFileContents._dotAssign_operation (GGS_string (true, "").reader_stringByLeftAndRightPadding (_inLexique, GGS_uint (true, 79U), GGS_char (true, '*') COMMA_SOURCE_FILE_AT_LINE (368))) ;
    var_cas_ioListFileContents.writeString ("\n"
      "\n") ;
  }
  GGS_symbolTableForOptimizations  var_cas_symbolTable ;
  var_cas_symbolTable = GGS_symbolTableForOptimizations ::constructor_emptyMap (_inLexique COMMA_HERE) ;
  {
      GGS_uint var_cas_lineIndex (true, 0) ;
    GGS_ipic_instructionList::cEnumerator enumerator_14463 (var_cas_ioGeneratedInstructionList, true) ;
    const GGS_ipic_instructionList::cElement * operand_14463 = NULL ;
    while (((operand_14463 = enumerator_14463.nextObject ()))) {
      macroValidPointer (operand_14463) ;
      const GGS_ipic_instruction  _temp_14521 = operand_14463->mInstruction ;
      if (_temp_14521._isBuilt ()) {
        typeCategoryMethod__ipic_instruction__defineLabel _method = findCategoryMethod__ipic_instruction__defineLabel (_temp_14521._galgasObjectRunTimeInfo ()) ;
        if (_method != NULL) {
          _method (_inLexique, _temp_14521 (HERE), var_cas_symbolTable, var_cas_lineIndex COMMA_SOURCE_FILE_AT_LINE (373)) ;
        }
      }
      var_cas_lineIndex.mValue ++ ;
    }
  }
  GGS_bool var_cas_optimizationsDone ;
  var_cas_optimizationsDone = GGS_bool (true, true) ;
  GGS_uint  var_cas_iteration ;
  var_cas_iteration = GGS_uint (true, 0U) ;
  GGS_uint _variant_18465 = var_cas_ioGeneratedInstructionList.reader_length (_inLexique COMMA_SOURCE_FILE_AT_LINE (378)) ;
  GGS_bool _condition_18465 (_variant_18465._isBuilt (), true) ;
  while (_condition_18465.isBuiltAndTrue ()) {
    _condition_18465 = var_cas_optimizationsDone ;
    if (_condition_18465.isBuiltAndTrue ()) {
      if (_variant_18465.uintValue () == 0) {
        _inLexique.onTheFlyRunTimeError ("loop variant error" COMMA_SOURCE_FILE_AT_LINE (450)) ;
        _condition_18465 = GGS_bool (true, false) ;
      }else{
        _variant_18465._decrement_operation (_inLexique COMMA_HERE) ;
        var_cas_optimizationsDone = GGS_bool (true, false) ;
        var_cas_iteration._increment_operation (_inLexique COMMA_SOURCE_FILE_AT_LINE (382)) ;
        if ((GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (383)))).isBuiltAndTrue ()) {
          var_cas_ioListFileContents.writeString ("Pass ") ;
          var_cas_ioListFileContents._dotAssign_operation (var_cas_iteration.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (384))) ;
          var_cas_ioListFileContents.writeString (":\n") ;
        }
        {
            GGS_uint var_cas_idx (true, 0) ;
          GGS_ipic_instructionList::cEnumerator enumerator_14992 (var_cas_ioGeneratedInstructionList, true) ;
          const GGS_ipic_instructionList::cElement * operand_14992 = NULL ;
          while (((operand_14992 = enumerator_14992.nextObject ()))) {
            macroValidPointer (operand_14992) ;
            { const GGS_ipic_instruction _var_16286 = operand_14992->mInstruction ; // CAST instruction
              if (_var_16286.getPtr () != NULL) {
                macroValidPointer (_var_16286.getPtr ()) ;
                if (typeid (cPtr_ipic_JUMP) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_JUMP var_cas_ipic_JUMP (_var_16286.getPtr ()) ;
                  const GGS_ipic_JUMP  _temp_15110 = var_cas_ipic_JUMP ;
                  if (_temp_15110._isBuilt ()) {
                    typeCategoryMethod__ipic_JUMP__optimizeJUMP _method = findCategoryMethod__ipic_JUMP__optimizeJUMP (_temp_15110._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_15110 (HERE), var_cas_symbolTable, var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (390)) ;
                    }
                  }
                }else if (typeid (cPtr_ipic_JSR) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_JSR var_cas_ipic_JSR (_var_16286.getPtr ()) ;
                  const GGS_ipic_JSR  _temp_15268 = var_cas_ipic_JSR ;
                  if (_temp_15268._isBuilt ()) {
                    typeCategoryMethod__ipic_JSR__optimizeJSR _method = findCategoryMethod__ipic_JSR__optimizeJSR (_temp_15268._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_15268 (HERE), var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (392)) ;
                    }
                  }
                }else if (typeid (cPtr_ipic_instruction_literalOperation) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_instruction_literalOperation var_cas_ipic_literal (_var_16286.getPtr ()) ;
                  const GGS_ipic_instruction_literalOperation  _temp_15445 = var_cas_ipic_literal ;
                  if (_temp_15445._isBuilt ()) {
                    typeCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW _method = findCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW (_temp_15445._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_15445 (HERE), var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (394)) ;
                    }
                  }
                }else if (typeid (cPtr_ipic_instruction_conditionalBranch) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_instruction_conditionalBranch var_cas_ipic_cc (_var_16286.getPtr ()) ;
                  const GGS_ipic_instruction_conditionalBranch  _temp_15615 = var_cas_ipic_cc ;
                  if (_temp_15615._isBuilt ()) {
                    typeCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC _method = findCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC (_temp_15615._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_15615 (HERE), var_cas_symbolTable, var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (396)) ;
                    }
                  }
                }else if (typeid (cPtr_ipic_jump_test_register) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_jump_test_register var_cas_ipic_testReg (_var_16286.getPtr ()) ;
                  const GGS_ipic_jump_test_register  _temp_15795 = var_cas_ipic_testReg ;
                  if (_temp_15795._isBuilt ()) {
                    typeCategoryMethod__ipic_jump_test_register__optimizeTestReg _method = findCategoryMethod__ipic_jump_test_register__optimizeTestReg (_temp_15795._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_15795 (HERE), var_cas_symbolTable, var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (398)) ;
                    }
                  }
                }else if (typeid (cPtr_ipic_incDecRegisterInCondition) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_incDecRegisterInCondition var_cas_ipic_decInc (_var_16286.getPtr ()) ;
                  const GGS_ipic_incDecRegisterInCondition  _temp_15984 = var_cas_ipic_decInc ;
                  if (_temp_15984._isBuilt ()) {
                    typeCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc _method = findCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc (_temp_15984._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_15984 (HERE), var_cas_symbolTable, var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (400)) ;
                    }
                  }
                }else if (typeid (cPtr_ipic_registerComparisonCondition) == typeid (* (_var_16286.getPtr ()))) {
                  const GGS_ipic_registerComparisonCondition var_cas_ipic_CMP (_var_16286.getPtr ()) ;
                  const GGS_ipic_registerComparisonCondition  _temp_16172 = var_cas_ipic_CMP ;
                  if (_temp_16172._isBuilt ()) {
                    typeCategoryMethod__ipic_registerComparisonCondition__optimizeCMP _method = findCategoryMethod__ipic_registerComparisonCondition__optimizeCMP (_temp_16172._galgasObjectRunTimeInfo ()) ;
                    if (_method != NULL) {
                      _method (_inLexique, _temp_16172 (HERE), var_cas_symbolTable, var_cas_idx, var_cas_ioGeneratedInstructionList, var_cas_ioListFileContents, var_cas_optimizationsDone COMMA_SOURCE_FILE_AT_LINE (402)) ;
                    }
                  }
                }else{
                }
              }
            }
            var_cas_idx.mValue ++ ;
          }
        }
        GGS_stringset  var_cas_referencedLabels ;
        var_cas_referencedLabels = GGS_stringset ::constructor_emptySet () ;
        {
          GGS_ipic_instructionList::cEnumerator enumerator_16414 (var_cas_ioGeneratedInstructionList, true) ;
          const GGS_ipic_instructionList::cElement * operand_16414 = NULL ;
          while (((operand_16414 = enumerator_16414.nextObject ()))) {
            macroValidPointer (operand_16414) ;
            const GGS_ipic_instruction  _temp_16464 = operand_16414->mInstruction ;
            if (_temp_16464._isBuilt ()) {
              _temp_16464 (HERE)->method_enterReferencedLabel (_inLexique, var_cas_referencedLabels COMMA_SOURCE_FILE_AT_LINE (409)) ;
            }
          }
        }
        {
          GGS_symbolTableForOptimizations::cEnumerator enumerator_16537 (var_cas_symbolTable, true) ;
          const GGS_symbolTableForOptimizations::cElement * operand_16537 = NULL ;
          while (((operand_16537 = enumerator_16537.nextObject ()))) {
            macroValidPointer (operand_16537) ;
            if (((var_cas_referencedLabels.reader_hasKey (_inLexique, operand_16537->mKey.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (412)) COMMA_SOURCE_FILE_AT_LINE (412)))._operator_not ()).isBuiltAndTrue ()) {
              GGS_uint  var_cas_definitionLine ;
              const GGS_symbolTableForOptimizations  _temp_16654 = var_cas_symbolTable ;
              if (_temp_16654._isBuilt ()) {
                _temp_16654 (HERE)->method_searchKey (_inLexique, operand_16537->mKey, var_cas_definitionLine COMMA_SOURCE_FILE_AT_LINE (413)) ;
              }
              var_cas_ioListFileContents.writeString ("  line ") ;
              var_cas_ioListFileContents._dotAssign_operation (var_cas_definitionLine.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (414))) ;
              var_cas_ioListFileContents.writeString (": unreferenced label '") ;
              var_cas_ioListFileContents._dotAssign_operation (operand_16537->mKey) ;
              var_cas_ioListFileContents.writeString ("' is deleted\n") ;
              var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_NULL ::constructor_new (_inLexique COMMA_HERE), var_cas_definitionLine COMMA_SOURCE_FILE_AT_LINE (415)) ;
              GGS_uint  automatic_var_0 ;
              var_cas_symbolTable.modifier_removeKey (_inLexique, operand_16537->mKey, automatic_var_0 COMMA_SOURCE_FILE_AT_LINE (416)) ;
            }
          }
        }
        GGS_bool var_cas_reachable ;
        var_cas_reachable = GGS_bool (true, true) ;
        GGS_bool var_cas_skippingInstruction ;
        var_cas_skippingInstruction = GGS_bool (true, false) ;
        GGS_bool var_cas_previousWasSkippingInstruction ;
        var_cas_previousWasSkippingInstruction = GGS_bool (true, false) ;
        {
            GGS_uint var_cas_idx (true, 0) ;
          GGS_ipic_instructionList::cEnumerator enumerator_17148 (var_cas_ioGeneratedInstructionList, true) ;
          const GGS_ipic_instructionList::cElement * operand_17148 = NULL ;
          while (((operand_17148 = enumerator_17148.nextObject ()))) {
            macroValidPointer (operand_17148) ;
            if (((var_cas_reachable)._operator_or (var_cas_previousWasSkippingInstruction)).isBuiltAndTrue ()) {
              const GGS_ipic_instruction  _temp_17264 = operand_17148->mInstruction ;
              if (_temp_17264._isBuilt ()) {
                _temp_17264 (HERE)->method_nextInstructionIsReachable (_inLexique, var_cas_reachable COMMA_SOURCE_FILE_AT_LINE (425)) ;
              }
              var_cas_previousWasSkippingInstruction = var_cas_skippingInstruction ;
              const GGS_ipic_instruction  _temp_17393 = operand_17148->mInstruction ;
              if (_temp_17393._isBuilt ()) {
                _temp_17393 (HERE)->method_isSkippingInstruction (_inLexique, var_cas_skippingInstruction COMMA_SOURCE_FILE_AT_LINE (427)) ;
              }
            }else{
              GGS_bool var_cas_isLABELorORG ;
              const GGS_ipic_instruction  _temp_17495 = operand_17148->mInstruction ;
              if (_temp_17495._isBuilt ()) {
                _temp_17495 (HERE)->method_isLABELorORG (_inLexique, var_cas_isLABELorORG COMMA_SOURCE_FILE_AT_LINE (429)) ;
              }
              GGS_bool var_cas_isNULL ;
              const GGS_ipic_instruction  _temp_17563 = operand_17148->mInstruction ;
              if (_temp_17563._isBuilt ()) {
                _temp_17563 (HERE)->method_isNULL (_inLexique, var_cas_isNULL COMMA_SOURCE_FILE_AT_LINE (430)) ;
              }
              if ((((var_cas_isLABELorORG)._operator_not ())._operator_and ((var_cas_isNULL)._operator_not ())).isBuiltAndTrue ()) {
                var_cas_ioListFileContents.writeString ("  line ") ;
                var_cas_ioListFileContents._dotAssign_operation (var_cas_idx.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (432))) ;
                var_cas_ioListFileContents.writeString (": unreachable instruction is deleted\n") ;
                var_cas_ioGeneratedInstructionList.modifier_setMInstructionAtIndex (_inLexique, GGS_ipic_NULL ::constructor_new (_inLexique COMMA_HERE), var_cas_idx COMMA_SOURCE_FILE_AT_LINE (433)) ;
              }else if ((var_cas_isLABELorORG).isBuiltAndTrue ()) {
                var_cas_reachable = GGS_bool (true, true) ;
                var_cas_previousWasSkippingInstruction = GGS_bool (true, false) ;
                var_cas_skippingInstruction = GGS_bool (true, false) ;
              }
            }
            var_cas_idx.mValue ++ ;
          }
        }
        if ((((var_cas_optimizationsDone)._operator_not ())._operator_and (GGS_bool (true, _inLexique.boolOptionValueFromKeys ("piccolo_options", "ouputListFile" COMMA_SOURCE_FILE_AT_LINE (442))))).isBuiltAndTrue ()) {
          var_cas_ioListFileContents.writeString ("  No optimization\n"
            "\n") ;
          GGS_uint  var_cas_currentAddress ;
          var_cas_currentAddress = GGS_uint (true, 0U) ;
          {
            GGS_ipic_instructionList::cEnumerator enumerator_18249 (var_cas_ioGeneratedInstructionList, true) ;
            const GGS_ipic_instructionList::cElement * operand_18249 = NULL ;
            while (((operand_18249 = enumerator_18249.nextObject ()))) {
              macroValidPointer (operand_18249) ;
              const GGS_ipic_instruction  _temp_18301 = operand_18249->mInstruction ;
              if (_temp_18301._isBuilt ()) {
                _temp_18301 (HERE)->method_setCurrentAddress (_inLexique, var_cas_currentAddress COMMA_SOURCE_FILE_AT_LINE (447)) ;
              }
            }
          }
          var_cas_ioListFileContents.writeString ("Minimum code size: ") ;
          var_cas_ioListFileContents._dotAssign_operation (var_cas_currentAddress.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (449))) ;
          var_cas_ioListFileContents.writeString (" bytes\n"
            "\n") ;
        }
      }
    }
  }
  #ifdef DEBUG_TRACE_ENABLED
    printf ("LEAVE routine_performOptimizations\n") ;
  #endif
}

//---------------------------------------------------------------------------*
//                                                                           *
//                      Prologue and epilogue actions                        *
//                                                                           *
//---------------------------------------------------------------------------*

static void prologueRoutineFor_ipic_optimizations (void) {
 enterCategoryMethod__ipic_instruction__defineLabel (category_method__ipic_instruction__defineLabel, gClassInfoFor__ipic_instruction.slotID ()) ;
 enterCategoryMethod__ipic_instruction__defineLabel ((typeCategoryMethod__ipic_instruction__defineLabel) category_method__ipic_pseudo_LABEL__defineLabel, gClassInfoFor__ipic_pseudo_LABEL.slotID ()) ;
 enterCategoryMethod__ipic_JUMP__optimizeJUMP (category_method__ipic_JUMP__optimizeJUMP, gClassInfoFor__ipic_JUMP.slotID ()) ;
 enterCategoryMethod__ipic_JSR__optimizeJSR (category_method__ipic_JSR__optimizeJSR, gClassInfoFor__ipic_JSR.slotID ()) ;
 enterCategoryMethod__ipic_instruction_literalOperation__optimizeMOVLW (category_method__ipic_instruction_literalOperation__optimizeMOVLW, gClassInfoFor__ipic_instruction_literalOperation.slotID ()) ;
 enterCategoryMethod__ipic_instruction_conditionalBranch__optimizeBCC (category_method__ipic_instruction_conditionalBranch__optimizeBCC, gClassInfoFor__ipic_instruction_conditionalBranch.slotID ()) ;
 enterCategoryMethod__ipic_jump_test_register__optimizeTestReg (category_method__ipic_jump_test_register__optimizeTestReg, gClassInfoFor__ipic_jump_test_register.slotID ()) ;
 enterCategoryMethod__ipic_incDecRegisterInCondition__optimizeTestDecInc (category_method__ipic_incDecRegisterInCondition__optimizeTestDecInc, gClassInfoFor__ipic_incDecRegisterInCondition.slotID ()) ;
 enterCategoryMethod__ipic_registerComparisonCondition__optimizeCMP (category_method__ipic_registerComparisonCondition__optimizeCMP, gClassInfoFor__ipic_registerComparisonCondition.slotID ()) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogueAction prologueEpilogueObjectFor_ipic_optimizations (prologueRoutineFor_ipic_optimizations,
                                   NULL) ;

//---------------------------------------------------------------------------*

