//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                         File 'ipic18_display_block_list.h'                                          *
//                                             Generated by version 3.0.0                                              *
//                                          october 4th, 2014, at 11h42'28"                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef ipic_31__38__5F_display_5F_block_5F_list_ENTITIES_DEFINED
#define ipic_31__38__5F_display_5F_block_5F_list_ENTITIES_DEFINED

//---------------------------------------------------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "ipic18_block_representation.h"
#include "pic18_metamodel.h"
#include "generic_metamodel.h"
#include "ipic18_regular_instructions.h"
#include "pic18_mnemonics.h"
#include "ipic18_terminators.h"

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                             Routine 'displayBlockList'                                              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_displayBlockList (const class GALGAS_string constinArgument0,
                               class GALGAS_string & ioArgument1,
                               const class GALGAS_ipic_31__38_BlockList constinArgument2,
                               class C_Compiler * inCompiler
                               COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                       Category method '@ipic18Block display'                                        *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void categoryMethod_display (const class GALGAS_ipic_31__38_Block inObject,
                             const class GALGAS_string constin_inNextBlockLabel,
                             class GALGAS_string & io_ioListFileContents,
                             class C_Compiler * inCompiler
                             COMMA_LOCATION_ARGS) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
