//---------------------------------------------------------------------------*
//                                                                           *
//               File 'midrange_ipic_build_assembly_code.cpp'                *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                    september 11th, 2008, at 19h39'37"                     *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*

#include "version_libpm.h"
#if LIBPM_VERSION != THE_LIBPM_VERSION
  #error "This file has been compiled with a version of GALGAS different than the version of libpm"
#endif

//---------------------------------------------------------------------------*

#include <typeinfo>
#include "utilities/MF_MemoryControl.h"
#include "files/C_TextFileWrite.h"
#include "midrange_ipic_build_assembly_code.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "midrange_ipic_build_assembly_code.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//Virtual Table for category method '@midrange_ipic_instruction.buildAssemblyCode'*
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode> gDispatchTableFor__midrange_ipic_instruction__buildAssemblyCode ;

//---------------------------------------------------------------------------*

void
enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode (typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode inRoutine,
                     const sint32 inClassID) {
  gDispatchTableFor__midrange_ipic_instruction__buildAssemblyCode.forceObjectAtIndex (inClassID, inRoutine, NULL) ;
}

//---------------------------------------------------------------------------*

typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode
findCategoryMethod__midrange_ipic_instruction__buildAssemblyCode (AC_galgasClassRunTimeInformation * inClassPtr) {
  typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode result = NULL ;
  if (inClassPtr->slotID () < gDispatchTableFor__midrange_ipic_instruction__buildAssemblyCode.count ()) {
    result = gDispatchTableFor__midrange_ipic_instruction__buildAssemblyCode (inClassPtr->slotID () COMMA_HERE) ;
  }
  if (result == NULL) {
    AC_galgasClassRunTimeInformation * superClassPtr = inClassPtr->superClassPtr () ;
    if (superClassPtr != NULL) {
      result = findCategoryMethod__midrange_ipic_instruction__buildAssemblyCode (superClassPtr) ;
      gDispatchTableFor__midrange_ipic_instruction__buildAssemblyCode.forceObjectAtIndex (inClassPtr->slotID (), result, NULL) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//         Category method '@midrange_ipic_NULL.buildAssemblyCode'           *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_NULL__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_NULL * operand_710,
                                GGS_string & /* var_cas_ioString */,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_710 != NULL) {
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//      Category method '@midrange_ipic_pseudo_ORG.buildAssemblyCode'        *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_pseudo_ORG__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_pseudo_ORG * operand_906,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_906 != NULL) {
    var_cas_ioString.writeString ("  ORG ") ;
    var_cas_ioString._dotAssign_operation (operand_906->mOrigin.reader_hexString (_inLexique COMMA_SOURCE_FILE_AT_LINE (30))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//     Category method '@midrange_ipic_pseudo_LABEL.buildAssemblyCode'       *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_pseudo_LABEL__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_pseudo_LABEL * operand_1150,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_1150 != NULL) {
    var_cas_ioString._dotAssign_operation (operand_1150->mLabel.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (39))) ;
    var_cas_ioString.writeString (":\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Category method '@midrange_ipic_instruction_FD.buildAssemblyCode'      *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_FD__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_instruction_FD * operand_1382,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_1382 != NULL) {
    var_cas_ioString.writeString ("  ") ;
    var_cas_ioString._dotAssign_operation (operand_1382->mInstruction_FD_base_code.reader_mnemonic (_inLexique COMMA_SOURCE_FILE_AT_LINE (48))) ;
    var_cas_ioString.writeString (" ") ;
    var_cas_ioString._dotAssign_operation (operand_1382->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (48))) ;
    if ((operand_1382->m_W_isDestination).isBuiltAndTrue ()) {
      var_cas_ioString.writeString (", W") ;
    }else{
      var_cas_ioString.writeString (", F") ;
    }
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Category method '@midrange_ipic_instruction_FB.buildAssemblyCode'      *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_FB__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_instruction_FB * operand_1796,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_1796 != NULL) {
    var_cas_ioString.writeString ("  ") ;
    var_cas_ioString._dotAssign_operation (operand_1796->mBitOrientedOp.reader_mnemonic (_inLexique COMMA_SOURCE_FILE_AT_LINE (63))) ;
    var_cas_ioString.writeString ("  ") ;
    var_cas_ioString._dotAssign_operation (operand_1796->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (64))) ;
    var_cas_ioString.writeString (", ") ;
    var_cas_ioString._dotAssign_operation (operand_1796->mBitNumber.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (65))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Category method '@midrange_ipic_instruction_BitTestSkip.buildAssemblyCode' *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_BitTestSkip__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_instruction_BitTestSkip * operand_2172,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_2172 != NULL) {
    var_cas_ioString.writeString ("  ") ;
    if ((operand_2172->mSkipIfSet).isBuiltAndTrue ()) {
      var_cas_ioString.writeString ("BTFSS") ;
    }else{
      var_cas_ioString.writeString ("BTFSC") ;
    }
    var_cas_ioString.writeString ("  ") ;
    var_cas_ioString._dotAssign_operation (operand_2172->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (81))) ;
    var_cas_ioString.writeString (", ") ;
    var_cas_ioString._dotAssign_operation (operand_2172->mBitNumber.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (82))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//     Category method '@midrange_ipic_instruction_F.buildAssemblyCode'      *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_F__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_instruction_F * operand_2601,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_2601 != NULL) {
    var_cas_ioString.writeString ("  ") ;
    var_cas_ioString._dotAssign_operation (operand_2601->mFinstruction.reader_mnemonic (_inLexique COMMA_SOURCE_FILE_AT_LINE (92))) ;
    var_cas_ioString.writeString (" ") ;
    var_cas_ioString._dotAssign_operation (operand_2601->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (92))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Category method '@midrange_ipic_incDecRegisterInCondition.buildAssemblyCode'*
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_incDecRegisterInCondition__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_incDecRegisterInCondition * operand_2920,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & var_cas_ioLocalLabelIndex
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_2920 != NULL) {
    if ((operand_2920->mIncrement).isBuiltAndTrue ()) {
      var_cas_ioString.writeString ("  "
      "INCFSZ ") ;
    }else{
      var_cas_ioString.writeString ("  "
      "DECFSZ ") ;
    }
    var_cas_ioString._dotAssign_operation (operand_2920->mRegisterDescription.reader_mAssemblyString (_inLexique COMMA_SOURCE_FILE_AT_LINE (107))) ;
    if ((operand_2920->m_W_isDestination).isBuiltAndTrue ()) {
      var_cas_ioString.writeString (", W") ;
    }else{
      var_cas_ioString.writeString (", F") ;
    }
    var_cas_ioString.writeString ("\n") ;
    if ((operand_2920->mBranchIfZero).isBuiltAndTrue ()) {
      GGS_string var_cas_localLabel ;
      var_cas_localLabel = (GGS_string (true, "_local_label_"))._operator_concat (var_cas_ioLocalLabelIndex.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (115))) ;
      var_cas_ioLocalLabelIndex._increment_operation (_inLexique COMMA_SOURCE_FILE_AT_LINE (115)) ;
      var_cas_ioString.writeString ("  GOTO ") ;
      var_cas_ioString._dotAssign_operation (var_cas_localLabel) ;
      var_cas_ioString.writeString ("\n") ;
      var_cas_ioString.writeString ("  GOTO ") ;
      var_cas_ioString._dotAssign_operation (operand_2920->mTargetLabel) ;
      var_cas_ioString.writeString ("\n") ;
      var_cas_ioString._dotAssign_operation (var_cas_localLabel) ;
      var_cas_ioString.writeString (":\n") ;
    }else{
      var_cas_ioString.writeString ("  GOTO ") ;
      var_cas_ioString._dotAssign_operation (operand_2920->mTargetLabel) ;
      var_cas_ioString.writeString ("\n") ;
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//         Category method '@midrange_ipic_JUMP.buildAssemblyCode'           *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_JUMP__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_JUMP * operand_3696,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_3696 != NULL) {
    switch (operand_3696->mBit11.enumValue ()) {
    case GGS_midrange_call_goto_bit::enum_set:
      {
      var_cas_ioString.writeString ("  BSF PCLATH, 3\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_clear:
      {
      var_cas_ioString.writeString ("  BCF PCLATH, 3\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_noChange:
      {
      }
      break ;
    case GGS_midrange_call_goto_bit::kNotBuilt:
      break ;
    }
    switch (operand_3696->mBit12.enumValue ()) {
    case GGS_midrange_call_goto_bit::enum_set:
      {
      var_cas_ioString.writeString ("  BSF PCLATH, 4\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_clear:
      {
      var_cas_ioString.writeString ("  BCF PCLATH, 4\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_noChange:
      {
      }
      break ;
    case GGS_midrange_call_goto_bit::kNotBuilt:
      break ;
    }
    var_cas_ioString.writeString ("  GOTO   ") ;
    var_cas_ioString._dotAssign_operation (operand_3696->mTargetLabel.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (140))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//         Category method '@midrange_ipic_GOTO.buildAssemblyCode'           *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_GOTO__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_GOTO * operand_4233,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_4233 != NULL) {
    var_cas_ioString.writeString ("  GOTO   ") ;
    var_cas_ioString._dotAssign_operation (operand_4233->mTargetLabel.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (149))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//          Category method '@midrange_ipic_JSR.buildAssemblyCode'           *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_JSR__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_JSR * operand_4473,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_4473 != NULL) {
    switch (operand_4473->mBit11.enumValue ()) {
    case GGS_midrange_call_goto_bit::enum_set:
      {
      var_cas_ioString.writeString ("  BSF PCLATH, 3\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_clear:
      {
      var_cas_ioString.writeString ("  BCF PCLATH, 3\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_noChange:
      {
      }
      break ;
    case GGS_midrange_call_goto_bit::kNotBuilt:
      break ;
    }
    switch (operand_4473->mBit12.enumValue ()) {
    case GGS_midrange_call_goto_bit::enum_set:
      {
      var_cas_ioString.writeString ("  BSF PCLATH, 4\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_clear:
      {
      var_cas_ioString.writeString ("  BCF PCLATH, 4\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_noChange:
      {
      }
      break ;
    case GGS_midrange_call_goto_bit::kNotBuilt:
      break ;
    }
    var_cas_ioString.writeString ("  CALL  ") ;
    var_cas_ioString._dotAssign_operation (operand_4473->mTargetLabel.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (168))) ;
    var_cas_ioString.writeString ("\n") ;
    switch (operand_4473->mBit11.enumValue ()) {
    case GGS_midrange_call_goto_bit::enum_set:
      {
      var_cas_ioString.writeString ("  BCF PCLATH, 3\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_clear:
      {
      var_cas_ioString.writeString ("  BSF PCLATH, 3\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_noChange:
      {
      }
      break ;
    case GGS_midrange_call_goto_bit::kNotBuilt:
      break ;
    }
    switch (operand_4473->mBit12.enumValue ()) {
    case GGS_midrange_call_goto_bit::enum_set:
      {
      var_cas_ioString.writeString ("  BCF PCLATH, 4\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_clear:
      {
      var_cas_ioString.writeString ("  BSF PCLATH, 4\n") ;
      }
      break ;
    case GGS_midrange_call_goto_bit::enum_noChange:
      {
      }
      break ;
    case GGS_midrange_call_goto_bit::kNotBuilt:
      break ;
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//         Category method '@midrange_ipic_CALL.buildAssemblyCode'           *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_CALL__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_CALL * operand_5305,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_5305 != NULL) {
    var_cas_ioString.writeString ("  CALL  ") ;
    var_cas_ioString._dotAssign_operation (operand_5305->mTargetLabel.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (187))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//  Category method '@midrange_ipic_instruction_CLRWDT.buildAssemblyCode'    *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_CLRWDT__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_instruction_CLRWDT * operand_5559,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_5559 != NULL) {
    var_cas_ioString.writeString ("  CLRWDT\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//   Category method '@midrange_ipic_instruction_CLRW.buildAssemblyCode'     *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_CLRW__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_instruction_CLRW * operand_5782,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_5782 != NULL) {
    var_cas_ioString.writeString ("  CLRW\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//    Category method '@midrange_ipic_instruction_NOP.buildAssemblyCode'     *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_NOP__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_instruction_NOP * operand_6002,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6002 != NULL) {
    var_cas_ioString.writeString ("  NOP\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//  Category method '@midrange_ipic_instruction_RETURN.buildAssemblyCode'    *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_RETURN__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_instruction_RETURN * operand_6224,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6224 != NULL) {
    var_cas_ioString.writeString ("  RETURN\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//  Category method '@midrange_ipic_instruction_RETFIE.buildAssemblyCode'    *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_RETFIE__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_instruction_RETFIE * operand_6450,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6450 != NULL) {
    var_cas_ioString.writeString ("  RETFIE\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//   Category method '@midrange_ipic_instruction_SLEEP.buildAssemblyCode'    *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_SLEEP__buildAssemblyCode (C_Compiler &,
                                const cPtr_midrange_ipic_instruction_SLEEP * operand_6675,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6675 != NULL) {
    var_cas_ioString.writeString ("  SLEEP\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//Category method '@midrange_ipic_instruction_literalOperation.buildAssemblyCode'*
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_literalOperation__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_instruction_literalOperation * operand_6909,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_6909 != NULL) {
    var_cas_ioString.writeString ("  ") ;
    var_cas_ioString._dotAssign_operation (operand_6909->mLiteralInstruction.reader_mnemonic (_inLexique COMMA_SOURCE_FILE_AT_LINE (250))) ;
    var_cas_ioString.writeString (" ") ;
    var_cas_ioString._dotAssign_operation (operand_6909->mLiteralValue.reader_hexString (_inLexique COMMA_SOURCE_FILE_AT_LINE (250))) ;
    var_cas_ioString.writeString ("\n") ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//   Category method '@midrange_ipic_instruction_MNOP.buildAssemblyCode'     *
//                                                                           *
//---------------------------------------------------------------------------*

static void
category_method__midrange_ipic_instruction_MNOP__buildAssemblyCode (C_Compiler & _inLexique,
                                const cPtr_midrange_ipic_instruction_MNOP * operand_7198,
                                GGS_string & var_cas_ioString,
                                GGS_uint  & /* var_cas_ioLocalLabelIndex */
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (operand_7198 != NULL) {
    if (((operand_7198->mOccurrenceFactor.reader_uint (_inLexique COMMA_SOURCE_FILE_AT_LINE (259)))._operator_isEqual (GGS_uint (true, 0U))).isBuiltAndTrue ()) {
      operand_7198->mOccurrenceFactor.reader_location (_inLexique COMMA_HERE).signalGGSSemanticWarning (_inLexique, GGS_string (true, "No generated code") COMMA_SOURCE_FILE_AT_LINE (260)) ;
    }
    GGS_uint  var_cas_idx ;
    var_cas_idx = GGS_uint (true, 0U) ;
    GGS_uint _variant_7504 = operand_7198->mOccurrenceFactor.reader_uint (_inLexique COMMA_SOURCE_FILE_AT_LINE (263)) ;
    GGS_bool _condition_7504 (_variant_7504._isBuilt (), true) ;
    while (_condition_7504.isBuiltAndTrue ()) {
      _condition_7504 = (var_cas_idx)._operator_strictInf (operand_7198->mOccurrenceFactor.reader_uint (_inLexique COMMA_SOURCE_FILE_AT_LINE (264))) ;
      if (_condition_7504.isBuiltAndTrue ()) {
        if (_variant_7504.uintValue () == 0) {
          _inLexique.onTheFlyRunTimeError ("loop variant error" COMMA_SOURCE_FILE_AT_LINE (268)) ;
          _condition_7504 = GGS_bool (true, false) ;
        }else{
          _variant_7504._decrement_operation (_inLexique COMMA_HERE) ;
          var_cas_ioString.writeString ("  NOP\n") ;
          var_cas_idx._increment_operation (_inLexique COMMA_SOURCE_FILE_AT_LINE (267)) ;
        }
      }
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//         Implementation of routine "midrange_build_assembly_code"          *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_midrange_build_assembly_code (C_Compiler & _inLexique,
                                const GGS_string  var_cas_inProcessorName,
                                const GGS_registerTable   var_cas_inPredefinedRegisters,
                                const GGS_registerTable   var_cas_inAllRegisters,
                                const GGS_midrange_ipic_instructionList   var_cas_inInstructionList,
                                const GGS_actualConfigurationMap   var_cas_inActualConfigurationMap,
                                GGS_string & var_cas_outAssemblyCode COMMA_UNUSED_LOCATION_ARGS) {
  #ifdef DEBUG_TRACE_ENABLED
    printf ("ENTER routine_midrange_build_assembly_code at %s:%d\n", __FILE__, __LINE__) ;
  #endif
  var_cas_outAssemblyCode = GGS_string (true, "  errorlevel -302 ; No Warning on registers not in bank 0\n") ;
  var_cas_outAssemblyCode = GGS_string (true, "  errorlevel -306 ; No Warning on crossing page boundary\n"
    "\n") ;
  var_cas_outAssemblyCode.writeString ("  PROCESSOR ") ;
  var_cas_outAssemblyCode._dotAssign_operation (var_cas_inProcessorName) ;
  var_cas_outAssemblyCode.writeString ("\n"
    "\n") ;
  var_cas_outAssemblyCode.writeString (";--- Code\n") ;
  var_cas_outAssemblyCode.writeString ("  ORG 0\n") ;
  GGS_uint  var_cas_bccLabelIndex ;
  var_cas_bccLabelIndex = GGS_uint (true, 0U) ;
  {
    GGS_midrange_ipic_instructionList::cEnumerator enumerator_9569 (var_cas_inInstructionList, true) ;
    const GGS_midrange_ipic_instructionList::cElement * operand_9569 = NULL ;
    while (((operand_9569 = enumerator_9569.nextObject ()))) {
      macroValidPointer (operand_9569) ;
      const GGS_midrange_ipic_instruction  _temp_9608 = operand_9569->mInstruction ;
      if (_temp_9608._isBuilt ()) {
        typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode _method = findCategoryMethod__midrange_ipic_instruction__buildAssemblyCode (_temp_9608._galgasObjectRunTimeInfo ()) ;
        if (_method != NULL) {
          _method (_inLexique, _temp_9608 (HERE), var_cas_outAssemblyCode, var_cas_bccLabelIndex COMMA_SOURCE_FILE_AT_LINE (337)) ;
        }
      }
    }
  }
  var_cas_outAssemblyCode.writeString ("\n") ;
  var_cas_outAssemblyCode.writeString (";--- Prefefined registers\n") ;
  {
    GGS_registerTable::cEnumerator enumerator_9798 (var_cas_inPredefinedRegisters, true) ;
    const GGS_registerTable::cElement * operand_9798 = NULL ;
    while (((operand_9798 = enumerator_9798.nextObject ()))) {
      macroValidPointer (operand_9798) ;
      GGS_uint  var_cas_firstRegister ;
      const GGS_uintlist  _temp_9855 = operand_9798->mInfo.mRegisterAddressList ;
      if (_temp_9855._isBuilt ()) {
        _temp_9855 (HERE)->method_first (_inLexique, var_cas_firstRegister COMMA_SOURCE_FILE_AT_LINE (343)) ;
      }
      var_cas_outAssemblyCode._dotAssign_operation (operand_9798->mKey.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (344))) ;
      var_cas_outAssemblyCode.writeString (" EQU ") ;
      var_cas_outAssemblyCode._dotAssign_operation (var_cas_firstRegister.reader_hexString (_inLexique COMMA_SOURCE_FILE_AT_LINE (344))) ;
      var_cas_outAssemblyCode.writeString ("\n") ;
    }
  }
  var_cas_outAssemblyCode.writeString ("\n") ;
  var_cas_outAssemblyCode.writeString (";--- User defined registers (in RAM)\n") ;
  {
    GGS_registerTable::cEnumerator enumerator_10124 (var_cas_inAllRegisters, true) ;
    const GGS_registerTable::cElement * operand_10124 = NULL ;
    while (((operand_10124 = enumerator_10124.nextObject ()))) {
      macroValidPointer (operand_10124) ;
      if (((var_cas_inPredefinedRegisters.reader_hasKey (_inLexique, operand_10124->mKey.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (350)) COMMA_SOURCE_FILE_AT_LINE (350)))._operator_not ()).isBuiltAndTrue ()) {
        GGS_uint  var_cas_firstRegister ;
        const GGS_uintlist  _temp_10244 = operand_10124->mInfo.mRegisterAddressList ;
        if (_temp_10244._isBuilt ()) {
          _temp_10244 (HERE)->method_first (_inLexique, var_cas_firstRegister COMMA_SOURCE_FILE_AT_LINE (351)) ;
        }
        var_cas_outAssemblyCode._dotAssign_operation (operand_10124->mKey.reader_string (_inLexique COMMA_SOURCE_FILE_AT_LINE (352))) ;
        var_cas_outAssemblyCode.writeString (" EQU ") ;
        var_cas_outAssemblyCode._dotAssign_operation (var_cas_firstRegister.reader_hexString (_inLexique COMMA_SOURCE_FILE_AT_LINE (352))) ;
        var_cas_outAssemblyCode.writeString ("\n") ;
      }
    }
  }
  var_cas_outAssemblyCode.writeString ("\n") ;
  var_cas_outAssemblyCode.writeString (";--- Piccolo defined symbol\n") ;
  var_cas_outAssemblyCode.writeString ("W EQU 1\n"
    "\n") ;
  if (((var_cas_inActualConfigurationMap.reader_count (_inLexique COMMA_SOURCE_FILE_AT_LINE (360)))._operator_strictSup (GGS_uint (true, 0U))).isBuiltAndTrue ()) {
    var_cas_outAssemblyCode.writeString (";--- Configuration\n"
      "\n") ;
    {
      GGS_actualConfigurationMap::cEnumerator enumerator_10711 (var_cas_inActualConfigurationMap, true) ;
      const GGS_actualConfigurationMap::cElement * operand_10711 = NULL ;
      while (((operand_10711 = enumerator_10711.nextObject ()))) {
        macroValidPointer (operand_10711) ;
        var_cas_outAssemblyCode.writeString ("  __config ") ;
        var_cas_outAssemblyCode._dotAssign_operation (operand_10711->mInfo.mRegisterAddress.reader_hexString (_inLexique COMMA_SOURCE_FILE_AT_LINE (363))) ;
        var_cas_outAssemblyCode.writeString (", ") ;
        var_cas_outAssemblyCode._dotAssign_operation ((operand_10711->mInfo.mRegisterValue)._operator_and (GGS_uint (true, 255U)).reader_hexString (_inLexique COMMA_SOURCE_FILE_AT_LINE (363))) ;
        var_cas_outAssemblyCode.writeString ("\n") ;
      }
    }
  }
  var_cas_outAssemblyCode.writeString (";---\n"
    "\n") ;
  var_cas_outAssemblyCode.writeString ("  END\n"
    "\n") ;
  #ifdef DEBUG_TRACE_ENABLED
    printf ("LEAVE routine_midrange_build_assembly_code\n") ;
  #endif
}

//---------------------------------------------------------------------------*
//                                                                           *
//                      Prologue and epilogue actions                        *
//                                                                           *
//---------------------------------------------------------------------------*

static void prologueRoutineFor_midrange_ipic_build_assembly_code (void) {
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_NULL__buildAssemblyCode, gClassInfoFor__midrange_ipic_NULL.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_pseudo_ORG__buildAssemblyCode, gClassInfoFor__midrange_ipic_pseudo_ORG.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_pseudo_LABEL__buildAssemblyCode, gClassInfoFor__midrange_ipic_pseudo_LABEL.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_FD__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_FD.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_FB__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_FB.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_BitTestSkip__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_BitTestSkip.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_F__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_F.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_incDecRegisterInCondition__buildAssemblyCode, gClassInfoFor__midrange_ipic_incDecRegisterInCondition.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_JUMP__buildAssemblyCode, gClassInfoFor__midrange_ipic_JUMP.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_GOTO__buildAssemblyCode, gClassInfoFor__midrange_ipic_GOTO.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_JSR__buildAssemblyCode, gClassInfoFor__midrange_ipic_JSR.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_CALL__buildAssemblyCode, gClassInfoFor__midrange_ipic_CALL.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_CLRWDT__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_CLRWDT.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_CLRW__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_CLRW.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_NOP__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_NOP.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_RETURN__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_RETURN.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_RETFIE__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_RETFIE.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_SLEEP__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_SLEEP.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_literalOperation__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_literalOperation.slotID ()) ;
 enterCategoryMethod__midrange_ipic_instruction__buildAssemblyCode ((typeCategoryMethod__midrange_ipic_instruction__buildAssemblyCode) category_method__midrange_ipic_instruction_MNOP__buildAssemblyCode, gClassInfoFor__midrange_ipic_instruction_MNOP.slotID ()) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogueAction prologueEpilogueObjectFor_midrange_ipic_build_assembly_code (prologueRoutineFor_midrange_ipic_build_assembly_code,
                                   NULL) ;

//---------------------------------------------------------------------------*

