//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'pic18_mnemonics.cpp'                         *
//                        Generated by version 2.5.4                         *
//                     january 30th, 2014, at 17h15'9"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "pic18_mnemonics.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//-----------------------------------------------------------------------------*


//-----------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "pic18_mnemonics.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//-----------------------------------------------------------------------------*
//                                                                             *
//                       Routine 'getComplementaryBcc'                       *
//                                                                             *
//-----------------------------------------------------------------------------*

void routine_getComplementaryBcc (const GALGAS_conditional_5F_branch constinArgument_inConditionalBranch,
                                  GALGAS_conditional_5F_branch & outArgument_outComplementary,
                                  C_Compiler * /* inCompiler */
                                  COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outComplementary.drop () ; // Release 'out' argument
  if (constinArgument_inConditionalBranch.isValid ()) {
    switch (constinArgument_inConditionalBranch.enumValue ()) {
    case GALGAS_conditional_5F_branch::kNotBuilt:
      break ;
    case GALGAS_conditional_5F_branch::kEnum_bz: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bnz (SOURCE_FILE_AT_LINE (93)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnz: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bz (SOURCE_FILE_AT_LINE (94)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bn: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bnn (SOURCE_FILE_AT_LINE (95)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnn: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bn (SOURCE_FILE_AT_LINE (96)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bc: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bnc (SOURCE_FILE_AT_LINE (97)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnc: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bc (SOURCE_FILE_AT_LINE (98)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bov: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bnov (SOURCE_FILE_AT_LINE (99)) ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnov: {
      outArgument_outComplementary = GALGAS_conditional_5F_branch::constructor_bov (SOURCE_FILE_AT_LINE (100)) ;
      } break ;
    }
  }
}


//---------------------------------------------------------------------------*
//                                                                           *
//            Category Reader '@pic18RegisterComparison mnemonic'            *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_mnemonic (const GALGAS_pic_31__38_RegisterComparison & inObject,
                                       C_Compiler * /* inCompiler */
                                       COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_pic_31__38_RegisterComparison temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_pic_31__38_RegisterComparison::kNotBuilt:
      break ;
    case GALGAS_pic_31__38_RegisterComparison::kEnum_notEqual: {
      result_outResult = GALGAS_string ("!=") ;
      } break ;
    case GALGAS_pic_31__38_RegisterComparison::kEnum_equal: {
      result_outResult = GALGAS_string ("==") ;
      } break ;
    case GALGAS_pic_31__38_RegisterComparison::kEnum_greaterOrEqual: {
      result_outResult = GALGAS_string (">=") ;
      } break ;
    case GALGAS_pic_31__38_RegisterComparison::kEnum_greater: {
      result_outResult = GALGAS_string (">") ;
      } break ;
    case GALGAS_pic_31__38_RegisterComparison::kEnum_lowerOrEqual: {
      result_outResult = GALGAS_string ("<=") ;
      } break ;
    case GALGAS_pic_31__38_RegisterComparison::kEnum_lower: {
      result_outResult = GALGAS_string ("<") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//              Category Reader '@conditional_branch condition'              *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_condition (const GALGAS_conditional_5F_branch & inObject,
                                        C_Compiler * /* inCompiler */
                                        COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_conditional_5F_branch temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_conditional_5F_branch::kNotBuilt:
      break ;
    case GALGAS_conditional_5F_branch::kEnum_bz: {
      result_outResult = GALGAS_string ("Z") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnz: {
      result_outResult = GALGAS_string ("NZ") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bn: {
      result_outResult = GALGAS_string ("N") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnn: {
      result_outResult = GALGAS_string ("NN") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bc: {
      result_outResult = GALGAS_string ("C") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnc: {
      result_outResult = GALGAS_string ("NC") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bov: {
      result_outResult = GALGAS_string ("OV") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnov: {
      result_outResult = GALGAS_string ("NOV") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//     Category Reader '@pic18InstructionWithNoOperandKind assemblyCode'     *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_assemblyCode (const GALGAS_pic_31__38_InstructionWithNoOperandKind & inObject,
                                           C_Compiler * /* inCompiler */
                                           COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_pic_31__38_InstructionWithNoOperandKind temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kNotBuilt:
      break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_CLRWDT: {
      result_outResult = GALGAS_string ("CLRWDT") ;
      } break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_DAW: {
      result_outResult = GALGAS_string ("DAW") ;
      } break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_NOP: {
      result_outResult = GALGAS_string ("NOP") ;
      } break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_POP: {
      result_outResult = GALGAS_string ("POP") ;
      } break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_PUSH: {
      result_outResult = GALGAS_string ("PUSH") ;
      } break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_RESET: {
      result_outResult = GALGAS_string ("RESET") ;
      } break ;
    case GALGAS_pic_31__38_InstructionWithNoOperandKind::kEnum_SLEEP: {
      result_outResult = GALGAS_string ("SLEEP") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//           Category Reader '@FA_instruction_base_code mnemonic'            *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_mnemonic (const GALGAS_FA_5F_instruction_5F_base_5F_code & inObject,
                                       C_Compiler * /* inCompiler */
                                       COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_FA_5F_instruction_5F_base_5F_code temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kNotBuilt:
      break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_CLRF: {
      result_outResult = GALGAS_string ("CLRF") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_CPFSEQ: {
      result_outResult = GALGAS_string ("CPFSEQ") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_CPFSGT: {
      result_outResult = GALGAS_string ("CPFSGT") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_CPFSLT: {
      result_outResult = GALGAS_string ("CPFSLT") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_MOVWF: {
      result_outResult = GALGAS_string ("MOVWF") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_MULWF: {
      result_outResult = GALGAS_string ("MULWF") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_NEGF: {
      result_outResult = GALGAS_string ("NEGF") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_SETF: {
      result_outResult = GALGAS_string ("SETF") ;
      } break ;
    case GALGAS_FA_5F_instruction_5F_base_5F_code::kEnum_TSTFSZ: {
      result_outResult = GALGAS_string ("TSTFSZ") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//                Category Reader '@bit_oriented_op mnemonic'                *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_mnemonic (const GALGAS_bit_5F_oriented_5F_op & inObject,
                                       C_Compiler * /* inCompiler */
                                       COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_bit_5F_oriented_5F_op temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_bit_5F_oriented_5F_op::kNotBuilt:
      break ;
    case GALGAS_bit_5F_oriented_5F_op::kEnum_BCF: {
      result_outResult = GALGAS_string ("BCF") ;
      } break ;
    case GALGAS_bit_5F_oriented_5F_op::kEnum_BSF: {
      result_outResult = GALGAS_string ("BSF") ;
      } break ;
    case GALGAS_bit_5F_oriented_5F_op::kEnum_BTG: {
      result_outResult = GALGAS_string ("BTG") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//              Category Reader '@conditional_branch mnemonic'               *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_mnemonic (const GALGAS_conditional_5F_branch & inObject,
                                       C_Compiler * /* inCompiler */
                                       COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_conditional_5F_branch temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_conditional_5F_branch::kNotBuilt:
      break ;
    case GALGAS_conditional_5F_branch::kEnum_bz: {
      result_outResult = GALGAS_string ("BZ") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnz: {
      result_outResult = GALGAS_string ("BNZ") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bn: {
      result_outResult = GALGAS_string ("BN") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnn: {
      result_outResult = GALGAS_string ("BNN") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bc: {
      result_outResult = GALGAS_string ("BC") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnc: {
      result_outResult = GALGAS_string ("BNC") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bov: {
      result_outResult = GALGAS_string ("BOV") ;
      } break ;
    case GALGAS_conditional_5F_branch::kEnum_bnov: {
      result_outResult = GALGAS_string ("BNOV") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//          Category Reader '@literal_instruction_opcode mnemonic'           *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_mnemonic (const GALGAS_literal_5F_instruction_5F_opcode & inObject,
                                       C_Compiler * /* inCompiler */
                                       COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_literal_5F_instruction_5F_opcode temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_literal_5F_instruction_5F_opcode::kNotBuilt:
      break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_ADDLW: {
      result_outResult = GALGAS_string ("ADDLW") ;
      } break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_ANDLW: {
      result_outResult = GALGAS_string ("ANDLW") ;
      } break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_IORLW: {
      result_outResult = GALGAS_string ("IORLW") ;
      } break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_MOVLW: {
      result_outResult = GALGAS_string ("MOVLW") ;
      } break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_MULLW: {
      result_outResult = GALGAS_string ("MULLW") ;
      } break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_SUBLW: {
      result_outResult = GALGAS_string ("SUBLW") ;
      } break ;
    case GALGAS_literal_5F_instruction_5F_opcode::kEnum_XORLW: {
      result_outResult = GALGAS_string ("XORLW") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------*
//                                                                           *
//               Category Reader '@tableAccessOption mnemonic'               *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string categoryReader_mnemonic (const GALGAS_tableAccessOption & inObject,
                                       C_Compiler * /* inCompiler */
                                       COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_tableAccessOption temp_0 = inObject ;
  if (temp_0.isValid ()) {
    switch (temp_0.enumValue ()) {
    case GALGAS_tableAccessOption::kNotBuilt:
      break ;
    case GALGAS_tableAccessOption::kEnum_simpleAccess: {
      result_outResult = GALGAS_string ("*") ;
      } break ;
    case GALGAS_tableAccessOption::kEnum_postIncrement: {
      result_outResult = GALGAS_string ("*+") ;
      } break ;
    case GALGAS_tableAccessOption::kEnum_postDecrement: {
      result_outResult = GALGAS_string ("*-") ;
      } break ;
    case GALGAS_tableAccessOption::kEnum_preIncrement: {
      result_outResult = GALGAS_string ("+*") ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


