//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                File 'pic18_bootloader_specification_semantics.cpp'                                  *
//                                             Generated by version 2.7.0                                              *
//                                           august 8th, 2014, at 20h3'53"                                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "piccolo_options.h"
#include "pic18_grammar.h"
#include "piccoloDevice_grammar.h"
#include "pic18_bootloader_specification_semantics.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                   Routine 'pic18BootloaderSpecificationAnalysis'                                    *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_pic_31__38_BootloaderSpecificationAnalysis (const GALGAS_string constinArgument_inSourceFileName,
                                                         const GALGAS_lstring constinArgument_inBootloaderName,
                                                         const GALGAS_lstring constinArgument_inDeviceName,
                                                         const GALGAS_routineDeclarationList constinArgument_inBootloaderRoutineDeclarationList,
                                                         const GALGAS_bootloaderReservedRAMmap constinArgument_inBootloaderReservedRAMmap,
                                                         const GALGAS_luint constinArgument_inReservedRomSize,
                                                         const GALGAS_routineDeclarationList constinArgument_inUserRoutineDeclarationList,
                                                         const GALGAS_ramDefinitionList constinArgument_inSharedRamDefinitionList,
                                                         GALGAS_string & outArgument_outListFileContents,
                                                         GALGAS_piccoloDeviceModel & outArgument_outPiccoloDeviceModel,
                                                         GALGAS_uint & outArgument_outAccessBankSplitOffset,
                                                         GALGAS_ramBankTable & outArgument_outRamBank,
                                                         GALGAS_registerTable & outArgument_outRegisterTable,
                                                         C_Compiler * inCompiler
                                                         COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outListFileContents.drop () ; // Release 'out' argument
  outArgument_outPiccoloDeviceModel.drop () ; // Release 'out' argument
  outArgument_outAccessBankSplitOffset.drop () ; // Release 'out' argument
  outArgument_outRamBank.drop () ; // Release 'out' argument
  outArgument_outRegisterTable.drop () ; // Release 'out' argument
  GALGAS_string var_sourceFileBaseName = constinArgument_inSourceFileName.reader_lastPathComponent (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 23)).reader_stringByDeletingPathExtension (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 23)) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_sourceFileBaseName.objectCompare (constinArgument_inBootloaderName.reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 24)))).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (constinArgument_inBootloaderName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("the bootloader name ('").operator_concat (constinArgument_inBootloaderName.reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 25))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 25)).operator_concat (GALGAS_string ("') should be identical to the file base name '")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 25)).operator_concat (var_sourceFileBaseName  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 26)).operator_concat (GALGAS_string ("'")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 26))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 25)) ;
  }
  outArgument_outListFileContents = GALGAS_string::makeEmptyString () ;
  {
  routine_parseDeviceDefinition (constinArgument_inDeviceName, outArgument_outPiccoloDeviceModel, inCompiler  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 30)) ;
  }
  if (outArgument_outPiccoloDeviceModel.reader_mProcessorType (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 31)).isValid ()) {
    switch (outArgument_outPiccoloDeviceModel.reader_mProcessorType (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 31)).enumValue ()) {
    case GALGAS_processorType::kNotBuilt:
      break ;
    case GALGAS_processorType::kEnum_pic_31__38__5F__36__30_: {
      outArgument_outAccessBankSplitOffset = GALGAS_uint ((uint32_t) 96U) ;
      } break ;
    case GALGAS_processorType::kEnum_pic_31__38__5F__38__30_: {
      outArgument_outAccessBankSplitOffset = GALGAS_uint ((uint32_t) 128U) ;
      } break ;
    case GALGAS_processorType::kEnum_midrange: {
      GALGAS_location location_2 (constinArgument_inDeviceName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("a midrange device is not accepted here")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 34)) ;
      outArgument_outAccessBankSplitOffset.drop () ; // Release error dropped variable
      } break ;
    case GALGAS_processorType::kEnum_baseline: {
      GALGAS_location location_3 (constinArgument_inDeviceName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_3, GALGAS_string ("a baseline device is not accepted here")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 35)) ;
      outArgument_outAccessBankSplitOffset.drop () ; // Release error dropped variable
      } break ;
    }
  }
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 38)).operator_concat (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 38))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 38)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("*").operator_concat (GALGAS_string ("BOOTLOADER FOOTPRINT").reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 77U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 39))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 39)).operator_concat (GALGAS_string ("*\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 39))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 39)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 40)).operator_concat (GALGAS_string ("\n"
    "\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 40))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 40)) ;
  const enumGalgasBool test_4 = GALGAS_bool (kIsSupOrEqual, constinArgument_inReservedRomSize.reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 41)).objectCompare (outArgument_outPiccoloDeviceModel.reader_mRomSize (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 41)).reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 41)))).boolEnum () ;
  if (kBoolTrue == test_4) {
    GALGAS_location location_5 (constinArgument_inReservedRomSize.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_5, GALGAS_string ("reserved size for bootloader (").operator_concat (constinArgument_inReservedRomSize.reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 43)).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 43))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 42)).operator_concat (GALGAS_string (" bytes) is greater than ROM size (")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 43)).operator_concat (outArgument_outPiccoloDeviceModel.reader_mRomSize (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 44)).reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 44)).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 44))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 43)).operator_concat (GALGAS_string (" bytes) of ")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 44)).operator_concat (constinArgument_inDeviceName.reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 44))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 44)).operator_concat (GALGAS_string (" micro controller")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 45))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 42)) ;
  }
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("ROM size : ").operator_concat (constinArgument_inReservedRomSize.reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 47)).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 47))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 47)).operator_concat (GALGAS_string (" bytes.\n"
    "\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 47))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 47)) ;
  outArgument_outRamBank = outArgument_outPiccoloDeviceModel.reader_mRamBankTable (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 49)) ;
  cEnumerator_bootloaderReservedRAMmap enumerator_2673 (constinArgument_inBootloaderReservedRAMmap, kEnumeration_up) ;
  while (enumerator_2673.hasCurrentObject ()) {
    GALGAS_uint var_firstAddress ;
    GALGAS_uint var_firstFreeAddress ;
    GALGAS_uint var_lastAddressPlusOne ;
    GALGAS_uintlist var_mirrorOffsetList ;
    outArgument_outRamBank.method_searchKey (enumerator_2673.current_lkey (HERE), var_firstAddress, var_firstFreeAddress, var_lastAddressPlusOne, var_mirrorOffsetList, inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 55)) ;
    var_firstFreeAddress = var_firstFreeAddress.add_operation (enumerator_2673.current_mReservedSize (HERE).reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 56)), inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 56)) ;
    const enumGalgasBool test_6 = GALGAS_bool (kIsStrictSup, var_firstFreeAddress.objectCompare (var_lastAddressPlusOne)).boolEnum () ;
    if (kBoolTrue == test_6) {
      GALGAS_location location_7 (enumerator_2673.current_mReservedSize (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_7, GALGAS_string ("reserved size is greater than size of '").operator_concat (enumerator_2673.current_lkey (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 58))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 58)).operator_concat (GALGAS_string ("' bank (")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 58)).operator_concat (var_lastAddressPlusOne.substract_operation (var_firstAddress, inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 59)).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 59))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 58)).operator_concat (GALGAS_string (" bytes)")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 59))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 58)) ;
    }else if (kBoolFalse == test_6) {
      {
      outArgument_outRamBank.modifier_setMFirstFreeAddressForKey (var_firstFreeAddress, enumerator_2673.current_lkey (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 61)), inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 61)) ;
      }
      outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("'").operator_concat (enumerator_2673.current_lkey (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)).operator_concat (GALGAS_string ("' RAM size : ")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)).operator_concat (enumerator_2673.current_mReservedSize (HERE).reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)).operator_concat (GALGAS_string (" bytes (from ")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)).operator_concat (var_firstAddress.reader_hexString (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 63))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)).operator_concat (GALGAS_string (" to ")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 63)).operator_concat (var_firstFreeAddress.substract_operation (GALGAS_uint ((uint32_t) 1U), inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 63)).reader_hexString (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 63))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 63)).operator_concat (GALGAS_string (").\n"
        "\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 63))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 62)) ;
    }
    enumerator_2673.gotoNextObject () ;
  }
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 67)).operator_concat (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 67))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 67)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("*").operator_concat (GALGAS_string ("BOOTLOADER ROUTINES").reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 77U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 68))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 68)).operator_concat (GALGAS_string ("*\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 68))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 68)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 69)).operator_concat (GALGAS_string ("\n"
    "\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 69))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 69)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("Routine").reader_stringByLeftPadding (GALGAS_uint ((uint32_t) 40U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 70)).operator_concat (GALGAS_string (" Entry point address\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 70))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 70)) ;
  GALGAS_stringset var_routineNameSet = GALGAS_stringset::constructor_emptySet (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 71)) ;
  GALGAS_uint var_entryPointAddress = GALGAS_uint ((uint32_t) 4U) ;
  cEnumerator_routineDeclarationList enumerator_4032 (constinArgument_inBootloaderRoutineDeclarationList, kEnumeration_up) ;
  while (enumerator_4032.hasCurrentObject ()) {
    const enumGalgasBool test_8 = var_routineNameSet.reader_hasKey (enumerator_4032.current_mRoutineName (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 74)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 74)).boolEnum () ;
    if (kBoolTrue == test_8) {
      GALGAS_location location_9 (enumerator_4032.current_mRoutineName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_9, GALGAS_string ("This routine is already declared")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 75)) ;
    }
    var_routineNameSet.addAssign_operation (enumerator_4032.current_mRoutineName (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 77))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 77)) ;
    outArgument_outListFileContents.dotAssign_operation (enumerator_4032.current_mRoutineName (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78)).reader_stringByLeftPadding (GALGAS_uint ((uint32_t) 40U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78)).operator_concat (GALGAS_string (" ")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78)).operator_concat (var_entryPointAddress.reader_hexString (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78)).operator_concat (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 78)) ;
    var_entryPointAddress = var_entryPointAddress.add_operation (GALGAS_uint ((uint32_t) 4U), inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 79)) ;
    const enumGalgasBool test_10 = GALGAS_bool (kIsEqual, var_entryPointAddress.objectCompare (GALGAS_uint ((uint32_t) 8U))).boolEnum () ;
    if (kBoolTrue == test_10) {
      var_entryPointAddress = GALGAS_uint ((uint32_t) 12U) ;
    }else if (kBoolFalse == test_10) {
      const enumGalgasBool test_11 = GALGAS_bool (kIsEqual, var_entryPointAddress.objectCompare (GALGAS_uint ((uint32_t) 24U))).boolEnum () ;
      if (kBoolTrue == test_11) {
        var_entryPointAddress = GALGAS_uint ((uint32_t) 28U) ;
      }
    }
    enumerator_4032.gotoNextObject () ;
  }
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 86)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 88)).operator_concat (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 88))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 88)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("*").operator_concat (GALGAS_string ("USER PROGRAM ROUTINES").reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 77U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 89))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 89)).operator_concat (GALGAS_string ("*\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 89))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 89)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 90)).operator_concat (GALGAS_string ("\n"
    "\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 90))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 90)) ;
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("Routine").reader_stringByLeftPadding (GALGAS_uint ((uint32_t) 40U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 91)).operator_concat (GALGAS_string (" Entry point address\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 91))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 91)) ;
  var_entryPointAddress = constinArgument_inReservedRomSize.reader_uint (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 92)) ;
  cEnumerator_routineDeclarationList enumerator_5104 (constinArgument_inUserRoutineDeclarationList, kEnumeration_up) ;
  while (enumerator_5104.hasCurrentObject ()) {
    const enumGalgasBool test_12 = var_routineNameSet.reader_hasKey (enumerator_5104.current_mRoutineName (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 94)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 94)).boolEnum () ;
    if (kBoolTrue == test_12) {
      GALGAS_location location_13 (enumerator_5104.current_mRoutineName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_13, GALGAS_string ("This routine is already declared")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 95)) ;
    }
    var_routineNameSet.addAssign_operation (enumerator_5104.current_mRoutineName (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 97))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 97)) ;
    outArgument_outListFileContents.dotAssign_operation (enumerator_5104.current_mRoutineName (HERE).reader_string (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98)).reader_stringByLeftPadding (GALGAS_uint ((uint32_t) 40U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98)).operator_concat (GALGAS_string (" ")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98)).operator_concat (var_entryPointAddress.reader_hexString (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98)).operator_concat (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 98)) ;
    var_entryPointAddress = var_entryPointAddress.add_operation (GALGAS_uint ((uint32_t) 4U), inCompiler COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 99)) ;
    enumerator_5104.gotoNextObject () ;
  }
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string ("\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 101)) ;
  outArgument_outRegisterTable = outArgument_outPiccoloDeviceModel.reader_mRegisterTable (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 103)) ;
  {
  GALGAS_declaredByteMap joker_5820_0 ; // Joker input parameter
  routine_analyze_5F_ram_5F_sections (GALGAS_string ("SHARED VARIABLES"), constinArgument_inSharedRamDefinitionList, outArgument_outRamBank, outArgument_outPiccoloDeviceModel.reader_mRegisterTable (SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 108)), outArgument_outListFileContents, outArgument_outRegisterTable, joker_5820_0, inCompiler  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 104)) ;
  }
  outArgument_outListFileContents.dotAssign_operation (GALGAS_string::makeEmptyString ().reader_stringByLeftAndRightPadding (GALGAS_uint ((uint32_t) 79U), GALGAS_char (TO_UNICODE (42)) COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 113)).operator_concat (GALGAS_string ("\n"
    "\n")  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 113))  COMMA_SOURCE_FILE ("pic18_bootloader_specification_semantics.gSemantics", 113)) ;
}


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


