//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'pic18_used_routines.h'                        *
//                        Generated by version 2.5.0                         *
//                     october 6th, 2013, at 18h45'18"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef pic18_used_routines_ENTITIES_DEFINED
#define pic18_used_routines_ENTITIES_DEFINED

//---------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------*

#include "pic18_metamodel.h"
#include "generic_metamodel.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                      Function 'computeUsedRoutines'                       *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_stringset function_computeUsedRoutines (const GALGAS_interruptDefinitionList & constinArgument0,
                                               const GALGAS_routineDefinitionList & constinArgument1,
                                               const GALGAS_routineDeclarationList & constinArgument2,
                                               const GALGAS_routineDeclarationList & constinArgument3,
                                               C_Compiler * inCompiler
                                               COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//    Abstract category method '@pic18PiccoloInstruction addUsedRoutines'    *
//                                                                           *
//---------------------------------------------------------------------------*

typedef void (*categoryMethodSignature_pic_31__38_PiccoloInstruction_addUsedRoutines) (const cPtr_pic_31__38_PiccoloInstruction * inObject,
                                                                                       GALGAS_stringset & ioArgument0,
                                                                                       C_Compiler * inCompiler
                                                                                       COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

void enterCategoryMethod_addUsedRoutines (const PMSInt32 inClassIndex,
                                          categoryMethodSignature_pic_31__38_PiccoloInstruction_addUsedRoutines inMethod) ;

//---------------------------------------------------------------------------*

void callCategoryMethod_addUsedRoutines (const cPtr_pic_31__38_PiccoloInstruction * inObject,
                                         GALGAS_stringset & io_ioUsedRoutines,
                                         C_Compiler * inCompiler
                                         COMMA_LOCATION_ARGS) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
