//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'piccolo_options.h'                          *
//                        Generated by version 2.4.3                         *
//                      june 15th, 2013, at 20h11'29"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef piccolo_options_0_DEFINED
#define piccolo_options_0_DEFINED

//---------------------------------------------------------------------------*

#include "command_line_interface/C_BoolCommandLineOption.h"
#include "command_line_interface/C_UIntCommandLineOption.h"
#include "command_line_interface/C_StringCommandLineOption.h"

//---------------------------------------------------------------------------*

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


//---------------------------------------------------------------------------*
//                                                                           *
//                               Bool options                                *
//                                                                           *
//---------------------------------------------------------------------------*

extern C_BoolCommandLineOption gOption_piccolo_5F_options_doNotComputeStackRequirements ;

extern C_BoolCommandLineOption gOption_piccolo_5F_options_generateAssembly ;

extern C_BoolCommandLineOption gOption_piccolo_5F_options_ouputListingFile ;

extern C_BoolCommandLineOption gOption_piccolo_5F_options_output_5F_C_5F_Array ;

extern C_BoolCommandLineOption gOption_piccolo_5F_options_performOptimizations ;

//---------------------------------------------------------------------------*
//                                                                           *
//                               UInt options                                *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*
//                                                                           *
//                              String options                               *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*

#endif
