//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'piccoloDevice_grammar.h'                       *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                       july 27th, 2008, at 12h4'24"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef GRAMMAR_piccoloDevice_grammar_HAS_BEEN_DEFINED
#define GRAMMAR_piccoloDevice_grammar_HAS_BEEN_DEFINED

//---------------------------------------------------------------------------*

#include "piccoloDevice_syntax.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

class piccoloDevice_grammar : public piccoloDevice_syntax {
  public : virtual void nt_start_symbol_ (piccoloDevice_lexique &,
                                GGS_piccoloDeviceModel &) ;
  public : static void _performSourceFileParsing_ (C_Compiler & _inCompiler,
                                GGS_string * _inSentStringPtr,
                                const GGS_lstring inFileName,
                                GGS_piccoloDeviceModel &
                                COMMA_LOCATION_ARGS) ;
  public : static void _performSourceStringParsing_ (C_Compiler & _inCompiler,
                                GGS_string * _inSentStringPtr,
                                const GGS_string inSourceString,
                                GGS_piccoloDeviceModel &
                                COMMA_LOCATION_ARGS) ;
  public : virtual sint16 select_piccoloDevice_syntax_0 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_1 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_piccoloDevice_syntax_2 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_3 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_4 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_5 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_6 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_piccoloDevice_syntax_7 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_8 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_piccoloDevice_syntax_9 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_10 (piccoloDevice_lexique &) ;
  public : virtual sint16 select_repeat_piccoloDevice_syntax_11 (piccoloDevice_lexique &) ;
} ;

//---------------------------------------------------------------------------*

#endif
